/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum HillsType implements EnumType {

    munro("munro"),

    corbett("corbett"),

    graham("graham"),

    donald("donald"),

    sub2000("sub2000"),

    wainwright("wainwright"),

    hewitt("hewitt"),

    other("other");

    private final String literal;

    private HillsType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "hills_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static HillsType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(HillsType.class, literal);
    }
    // @formatter:on
}
