/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum SitesGroundtype implements EnumType {

    paved("paved"),

    grass("grass"),

    gravel("gravel"),

    sand("sand");

    private final String literal;

    private SitesGroundtype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "sites_groundtype";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static SitesGroundtype lookupLiteral(String literal) {
        return EnumType.lookupLiteral(SitesGroundtype.class, literal);
    }
    // @formatter:on
}
