/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.Hikestats;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HikestatsRecord extends UpdatableRecordImpl<HikestatsRecord> implements Record9<Integer, Integer, Double, Double, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.hikestats.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.hikestats.duration</code>.
     */
    public void setDuration(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>blog_db.hikestats.distance</code>.
     */
    public void setDistance(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.distance</code>.
     */
    public Double getDistance() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>blog_db.hikestats.ascent</code>.
     */
    public void setAscent(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.ascent</code>.
     */
    public Double getAscent() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>blog_db.hikestats.gpx_path</code>.
     */
    public void setGpxPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.gpx_path</code>.
     */
    public String getGpxPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>blog_db.hikestats.elevation_profile_path</code>.
     */
    public void setElevationProfilePath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.elevation_profile_path</code>.
     */
    public String getElevationProfilePath() {
        return (String) get(5);
    }

    /**
     * Setter for <code>blog_db.hikestats.time_distance_profile_path</code>.
     */
    public void setTimeDistanceProfilePath(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.time_distance_profile_path</code>.
     */
    public String getTimeDistanceProfilePath() {
        return (String) get(6);
    }

    /**
     * Setter for <code>blog_db.hikestats.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>blog_db.hikestats.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>blog_db.hikestats.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Double, Double, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Double, Double, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Hikestats.HIKESTATS.POST_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Hikestats.HIKESTATS.DURATION;
    }

    @Override
    public Field<Double> field3() {
        return Hikestats.HIKESTATS.DISTANCE;
    }

    @Override
    public Field<Double> field4() {
        return Hikestats.HIKESTATS.ASCENT;
    }

    @Override
    public Field<String> field5() {
        return Hikestats.HIKESTATS.GPX_PATH;
    }

    @Override
    public Field<String> field6() {
        return Hikestats.HIKESTATS.ELEVATION_PROFILE_PATH;
    }

    @Override
    public Field<String> field7() {
        return Hikestats.HIKESTATS.TIME_DISTANCE_PROFILE_PATH;
    }

    @Override
    public Field<Timestamp> field8() {
        return Hikestats.HIKESTATS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field9() {
        return Hikestats.HIKESTATS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getPostId();
    }

    @Override
    public Integer component2() {
        return getDuration();
    }

    @Override
    public Double component3() {
        return getDistance();
    }

    @Override
    public Double component4() {
        return getAscent();
    }

    @Override
    public String component5() {
        return getGpxPath();
    }

    @Override
    public String component6() {
        return getElevationProfilePath();
    }

    @Override
    public String component7() {
        return getTimeDistanceProfilePath();
    }

    @Override
    public Timestamp component8() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component9() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getPostId();
    }

    @Override
    public Integer value2() {
        return getDuration();
    }

    @Override
    public Double value3() {
        return getDistance();
    }

    @Override
    public Double value4() {
        return getAscent();
    }

    @Override
    public String value5() {
        return getGpxPath();
    }

    @Override
    public String value6() {
        return getElevationProfilePath();
    }

    @Override
    public String value7() {
        return getTimeDistanceProfilePath();
    }

    @Override
    public Timestamp value8() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value9() {
        return getUpdatedOn();
    }

    @Override
    public HikestatsRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public HikestatsRecord value2(Integer value) {
        setDuration(value);
        return this;
    }

    @Override
    public HikestatsRecord value3(Double value) {
        setDistance(value);
        return this;
    }

    @Override
    public HikestatsRecord value4(Double value) {
        setAscent(value);
        return this;
    }

    @Override
    public HikestatsRecord value5(String value) {
        setGpxPath(value);
        return this;
    }

    @Override
    public HikestatsRecord value6(String value) {
        setElevationProfilePath(value);
        return this;
    }

    @Override
    public HikestatsRecord value7(String value) {
        setTimeDistanceProfilePath(value);
        return this;
    }

    @Override
    public HikestatsRecord value8(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public HikestatsRecord value9(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public HikestatsRecord values(Integer value1, Integer value2, Double value3, Double value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HikestatsRecord
     */
    public HikestatsRecord() {
        super(Hikestats.HIKESTATS);
    }

    /**
     * Create a detached, initialised HikestatsRecord
     */
    public HikestatsRecord(Integer postId, Integer duration, Double distance, Double ascent, String gpxPath, String elevationProfilePath, String timeDistanceProfilePath, Timestamp createdOn, Timestamp updatedOn) {
        super(Hikestats.HIKESTATS);

        setPostId(postId);
        setDuration(duration);
        setDistance(distance);
        setAscent(ascent);
        setGpxPath(gpxPath);
        setElevationProfilePath(elevationProfilePath);
        setTimeDistanceProfilePath(timeDistanceProfilePath);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised HikestatsRecord
     */
    public HikestatsRecord(blog.raubach.database.codegen.tables.pojos.Hikestats value) {
        super(Hikestats.HIKESTATS);

        if (value != null) {
            setPostId(value.getPostId());
            setDuration(value.getDuration());
            setDistance(value.getDistance());
            setAscent(value.getAscent());
            setGpxPath(value.getGpxPath());
            setElevationProfilePath(value.getElevationProfilePath());
            setTimeDistanceProfilePath(value.getTimeDistanceProfilePath());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
