/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.ImageDetails;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageDetailsRecord extends TableRecordImpl<ImageDetailsRecord> implements Record5<Integer, String, Integer, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.image_details.image_id</code>.
     */
    public void setImageId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.image_details.image_id</code>.
     */
    public Integer getImageId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.image_details.image_path</code>.
     */
    public void setImagePath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.image_details.image_path</code>.
     */
    public String getImagePath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.image_details.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.image_details.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>blog_db.image_details.is_primary</code>.
     */
    public void setIsPrimary(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.image_details.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>blog_db.image_details.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.image_details.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Boolean, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Boolean, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ImageDetails.IMAGE_DETAILS.IMAGE_ID;
    }

    @Override
    public Field<String> field2() {
        return ImageDetails.IMAGE_DETAILS.IMAGE_PATH;
    }

    @Override
    public Field<Integer> field3() {
        return ImageDetails.IMAGE_DETAILS.POST_ID;
    }

    @Override
    public Field<Boolean> field4() {
        return ImageDetails.IMAGE_DETAILS.IS_PRIMARY;
    }

    @Override
    public Field<String> field5() {
        return ImageDetails.IMAGE_DETAILS.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getImageId();
    }

    @Override
    public String component2() {
        return getImagePath();
    }

    @Override
    public Integer component3() {
        return getPostId();
    }

    @Override
    public Boolean component4() {
        return getIsPrimary();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getImageId();
    }

    @Override
    public String value2() {
        return getImagePath();
    }

    @Override
    public Integer value3() {
        return getPostId();
    }

    @Override
    public Boolean value4() {
        return getIsPrimary();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public ImageDetailsRecord value1(Integer value) {
        setImageId(value);
        return this;
    }

    @Override
    public ImageDetailsRecord value2(String value) {
        setImagePath(value);
        return this;
    }

    @Override
    public ImageDetailsRecord value3(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public ImageDetailsRecord value4(Boolean value) {
        setIsPrimary(value);
        return this;
    }

    @Override
    public ImageDetailsRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ImageDetailsRecord values(Integer value1, String value2, Integer value3, Boolean value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageDetailsRecord
     */
    public ImageDetailsRecord() {
        super(ImageDetails.IMAGE_DETAILS);
    }

    /**
     * Create a detached, initialised ImageDetailsRecord
     */
    public ImageDetailsRecord(Integer imageId, String imagePath, Integer postId, Boolean isPrimary, String description) {
        super(ImageDetails.IMAGE_DETAILS);

        setImageId(imageId);
        setImagePath(imagePath);
        setPostId(postId);
        setIsPrimary(isPrimary);
        setDescription(description);
    }

    /**
     * Create a detached, initialised ImageDetailsRecord
     */
    public ImageDetailsRecord(blog.raubach.database.codegen.tables.pojos.ImageDetails value) {
        super(ImageDetails.IMAGE_DETAILS);

        if (value != null) {
            setImageId(value.getImageId());
            setImagePath(value.getImagePath());
            setPostId(value.getPostId());
            setIsPrimary(value.getIsPrimary());
            setDescription(value.getDescription());
        }
    }
    // @formatter:on
}
