/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.Postimages;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostimagesRecord extends UpdatableRecordImpl<PostimagesRecord> implements Record4<Integer, Integer, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.postimages.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.postimages.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.postimages.image_id</code>.
     */
    public void setImageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.postimages.image_id</code>.
     */
    public Integer getImageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>blog_db.postimages.is_primary</code>.
     */
    public void setIsPrimary(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.postimages.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>blog_db.postimages.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.postimages.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Boolean, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Boolean, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Postimages.POSTIMAGES.POST_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Postimages.POSTIMAGES.IMAGE_ID;
    }

    @Override
    public Field<Boolean> field3() {
        return Postimages.POSTIMAGES.IS_PRIMARY;
    }

    @Override
    public Field<String> field4() {
        return Postimages.POSTIMAGES.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getPostId();
    }

    @Override
    public Integer component2() {
        return getImageId();
    }

    @Override
    public Boolean component3() {
        return getIsPrimary();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getPostId();
    }

    @Override
    public Integer value2() {
        return getImageId();
    }

    @Override
    public Boolean value3() {
        return getIsPrimary();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public PostimagesRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public PostimagesRecord value2(Integer value) {
        setImageId(value);
        return this;
    }

    @Override
    public PostimagesRecord value3(Boolean value) {
        setIsPrimary(value);
        return this;
    }

    @Override
    public PostimagesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public PostimagesRecord values(Integer value1, Integer value2, Boolean value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostimagesRecord
     */
    public PostimagesRecord() {
        super(Postimages.POSTIMAGES);
    }

    /**
     * Create a detached, initialised PostimagesRecord
     */
    public PostimagesRecord(Integer postId, Integer imageId, Boolean isPrimary, String description) {
        super(Postimages.POSTIMAGES);

        setPostId(postId);
        setImageId(imageId);
        setIsPrimary(isPrimary);
        setDescription(description);
    }

    /**
     * Create a detached, initialised PostimagesRecord
     */
    public PostimagesRecord(blog.raubach.database.codegen.tables.pojos.Postimages value) {
        super(Postimages.POSTIMAGES);

        if (value != null) {
            setPostId(value.getPostId());
            setImageId(value.getImageId());
            setIsPrimary(value.getIsPrimary());
            setDescription(value.getDescription());
        }
    }
    // @formatter:on
}
