/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.PostIndividuals;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostIndividualsRecord extends UpdatableRecordImpl<PostIndividualsRecord> implements Record5<Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.post_individuals.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.post_individuals.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.post_individuals.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.post_individuals.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>blog_db.post_individuals.individual_id</code>.
     */
    public void setIndividualId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.post_individuals.individual_id</code>.
     */
    public Integer getIndividualId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>blog_db.post_individuals.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.post_individuals.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>blog_db.post_individuals.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.post_individuals.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PostIndividuals.POST_INDIVIDUALS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PostIndividuals.POST_INDIVIDUALS.POST_ID;
    }

    @Override
    public Field<Integer> field3() {
        return PostIndividuals.POST_INDIVIDUALS.INDIVIDUAL_ID;
    }

    @Override
    public Field<Timestamp> field4() {
        return PostIndividuals.POST_INDIVIDUALS.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field5() {
        return PostIndividuals.POST_INDIVIDUALS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPostId();
    }

    @Override
    public Integer component3() {
        return getIndividualId();
    }

    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPostId();
    }

    @Override
    public Integer value3() {
        return getIndividualId();
    }

    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    @Override
    public PostIndividualsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PostIndividualsRecord value2(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public PostIndividualsRecord value3(Integer value) {
        setIndividualId(value);
        return this;
    }

    @Override
    public PostIndividualsRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public PostIndividualsRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public PostIndividualsRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostIndividualsRecord
     */
    public PostIndividualsRecord() {
        super(PostIndividuals.POST_INDIVIDUALS);
    }

    /**
     * Create a detached, initialised PostIndividualsRecord
     */
    public PostIndividualsRecord(Integer id, Integer postId, Integer individualId, Timestamp createdOn, Timestamp updatedOn) {
        super(PostIndividuals.POST_INDIVIDUALS);

        setId(id);
        setPostId(postId);
        setIndividualId(individualId);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised PostIndividualsRecord
     */
    public PostIndividualsRecord(blog.raubach.database.codegen.tables.pojos.PostIndividuals value) {
        super(PostIndividuals.POST_INDIVIDUALS);

        if (value != null) {
            setId(value.getId());
            setPostId(value.getPostId());
            setIndividualId(value.getIndividualId());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
    // @formatter:on
}
