/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.Posthills;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosthillsRecord extends UpdatableRecordImpl<PosthillsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1114834274;

    /**
     * Setter for <code>blog_db.posthills.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.posthills.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.posthills.hill_id</code>.
     */
    public void setHillId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.posthills.hill_id</code>.
     */
    public Integer getHillId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Posthills.POSTHILLS.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Posthills.POSTHILLS.HILL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getHillId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getHillId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PosthillsRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PosthillsRecord value2(Integer value) {
        setHillId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PosthillsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PosthillsRecord
     */
    public PosthillsRecord() {
        super(Posthills.POSTHILLS);
    }

    /**
     * Create a detached, initialised PosthillsRecord
     */
    public PosthillsRecord(Integer postId, Integer hillId) {
        super(Posthills.POSTHILLS);

        set(0, postId);
        set(1, hillId);
    }
// @formatter:on
}
