/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.enums.PostsitesGroundtype;
import blog.raubach.database.codegen.tables.Postsites;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsitesRecord extends UpdatableRecordImpl<PostsitesRecord> implements Record3<Integer, Integer, PostsitesGroundtype> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.postsites.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.postsites.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.postsites.site_id</code>.
     */
    public void setSiteId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.postsites.site_id</code>.
     */
    public Integer getSiteId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>blog_db.postsites.groundtype</code>.
     */
    public void setGroundtype(PostsitesGroundtype value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.postsites.groundtype</code>.
     */
    public PostsitesGroundtype getGroundtype() {
        return (PostsitesGroundtype) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, PostsitesGroundtype> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, PostsitesGroundtype> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Postsites.POSTSITES.POST_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Postsites.POSTSITES.SITE_ID;
    }

    @Override
    public Field<PostsitesGroundtype> field3() {
        return Postsites.POSTSITES.GROUNDTYPE;
    }

    @Override
    public Integer component1() {
        return getPostId();
    }

    @Override
    public Integer component2() {
        return getSiteId();
    }

    @Override
    public PostsitesGroundtype component3() {
        return getGroundtype();
    }

    @Override
    public Integer value1() {
        return getPostId();
    }

    @Override
    public Integer value2() {
        return getSiteId();
    }

    @Override
    public PostsitesGroundtype value3() {
        return getGroundtype();
    }

    @Override
    public PostsitesRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public PostsitesRecord value2(Integer value) {
        setSiteId(value);
        return this;
    }

    @Override
    public PostsitesRecord value3(PostsitesGroundtype value) {
        setGroundtype(value);
        return this;
    }

    @Override
    public PostsitesRecord values(Integer value1, Integer value2, PostsitesGroundtype value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostsitesRecord
     */
    public PostsitesRecord() {
        super(Postsites.POSTSITES);
    }

    /**
     * Create a detached, initialised PostsitesRecord
     */
    public PostsitesRecord(Integer postId, Integer siteId, PostsitesGroundtype groundtype) {
        super(Postsites.POSTSITES);

        setPostId(postId);
        setSiteId(siteId);
        setGroundtype(groundtype);
    }

    /**
     * Create a detached, initialised PostsitesRecord
     */
    public PostsitesRecord(blog.raubach.database.codegen.tables.pojos.Postsites value) {
        super(Postsites.POSTSITES);

        if (value != null) {
            setPostId(value.getPostId());
            setSiteId(value.getSiteId());
            setGroundtype(value.getGroundtype());
        }
    }
    // @formatter:on
}
