/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.Posthills;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosthillsRecord extends UpdatableRecordImpl<PosthillsRecord> implements Record3<Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.posthills.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.posthills.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.posthills.hill_id</code>.
     */
    public void setHillId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.posthills.hill_id</code>.
     */
    public Integer getHillId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>blog_db.posthills.successful</code>.
     */
    public void setSuccessful(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.posthills.successful</code>.
     */
    public Boolean getSuccessful() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Posthills.POSTHILLS.POST_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Posthills.POSTHILLS.HILL_ID;
    }

    @Override
    public Field<Boolean> field3() {
        return Posthills.POSTHILLS.SUCCESSFUL;
    }

    @Override
    public Integer component1() {
        return getPostId();
    }

    @Override
    public Integer component2() {
        return getHillId();
    }

    @Override
    public Boolean component3() {
        return getSuccessful();
    }

    @Override
    public Integer value1() {
        return getPostId();
    }

    @Override
    public Integer value2() {
        return getHillId();
    }

    @Override
    public Boolean value3() {
        return getSuccessful();
    }

    @Override
    public PosthillsRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public PosthillsRecord value2(Integer value) {
        setHillId(value);
        return this;
    }

    @Override
    public PosthillsRecord value3(Boolean value) {
        setSuccessful(value);
        return this;
    }

    @Override
    public PosthillsRecord values(Integer value1, Integer value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PosthillsRecord
     */
    public PosthillsRecord() {
        super(Posthills.POSTHILLS);
    }

    /**
     * Create a detached, initialised PosthillsRecord
     */
    public PosthillsRecord(Integer postId, Integer hillId, Boolean successful) {
        super(Posthills.POSTHILLS);

        setPostId(postId);
        setHillId(hillId);
        setSuccessful(successful);
    }

    /**
     * Create a detached, initialised PosthillsRecord
     */
    public PosthillsRecord(blog.raubach.database.codegen.tables.pojos.Posthills value) {
        super(Posthills.POSTHILLS);

        if (value != null) {
            setPostId(value.getPostId());
            setHillId(value.getHillId());
            setSuccessful(value.getSuccessful());
        }
    }
    // @formatter:on
}
