/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.tables.Storyposts;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StorypostsRecord extends UpdatableRecordImpl<StorypostsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.storyposts.story_id</code>.
     */
    public void setStoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.storyposts.story_id</code>.
     */
    public Integer getStoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.storyposts.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.storyposts.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Storyposts.STORYPOSTS.STORY_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Storyposts.STORYPOSTS.POST_ID;
    }

    @Override
    public Integer component1() {
        return getStoryId();
    }

    @Override
    public Integer component2() {
        return getPostId();
    }

    @Override
    public Integer value1() {
        return getStoryId();
    }

    @Override
    public Integer value2() {
        return getPostId();
    }

    @Override
    public StorypostsRecord value1(Integer value) {
        setStoryId(value);
        return this;
    }

    @Override
    public StorypostsRecord value2(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public StorypostsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StorypostsRecord
     */
    public StorypostsRecord() {
        super(Storyposts.STORYPOSTS);
    }

    /**
     * Create a detached, initialised StorypostsRecord
     */
    public StorypostsRecord(Integer storyId, Integer postId) {
        super(Storyposts.STORYPOSTS);

        setStoryId(storyId);
        setPostId(postId);
    }

    /**
     * Create a detached, initialised StorypostsRecord
     */
    public StorypostsRecord(blog.raubach.database.codegen.tables.pojos.Storyposts value) {
        super(Storyposts.STORYPOSTS);

        if (value != null) {
            setStoryId(value.getStoryId());
            setPostId(value.getPostId());
        }
    }
    // @formatter:on
}
