/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.enums.PostsType;
import blog.raubach.database.codegen.tables.ViewPosts;
import blog.raubach.pojo.view.HikeRating;
import blog.raubach.pojo.view.HikeStats;
import blog.raubach.pojo.view.PostHill;
import blog.raubach.pojo.view.PostImage;
import blog.raubach.pojo.view.PostPerson;
import blog.raubach.pojo.view.PostSite;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewPostsRecord extends TableRecordImpl<ViewPostsRecord> implements Record17<Integer, PostsType, String, String, String, Boolean, Integer, Timestamp, Timestamp, PostHill[], PostPerson[], HikeStats, HikeRating, String[], Integer[], PostImage[], PostSite[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.view_posts.post_id</code>.
     */
    public void setPostId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_type</code>.
     */
    public void setPostType(PostsType value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_type</code>.
     */
    public PostsType getPostType() {
        return (PostsType) get(1);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_title</code>.
     */
    public void setPostTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_title</code>.
     */
    public String getPostTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_content</code>.
     */
    public void setPostContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_content</code>.
     */
    public String getPostContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_markdown</code>.
     */
    public void setPostMarkdown(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_markdown</code>.
     */
    public String getPostMarkdown() {
        return (String) get(4);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_visible</code>.
     */
    public void setPostVisible(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_visible</code>.
     */
    public Boolean getPostVisible() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_view_count</code>.
     */
    public void setPostViewCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_view_count</code>.
     */
    public Integer getPostViewCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_start_date</code>.
     */
    public void setPostStartDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_start_date</code>.
     */
    public Timestamp getPostStartDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>blog_db.view_posts.post_end_date</code>.
     */
    public void setPostEndDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.post_end_date</code>.
     */
    public Timestamp getPostEndDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>blog_db.view_posts.hills</code>.
     */
    public void setHills(PostHill[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.hills</code>.
     */
    public PostHill[] getHills() {
        return (PostHill[]) get(9);
    }

    /**
     * Setter for <code>blog_db.view_posts.people</code>.
     */
    public void setPeople(PostPerson[] value) {
        set(10, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.people</code>.
     */
    public PostPerson[] getPeople() {
        return (PostPerson[]) get(10);
    }

    /**
     * Setter for <code>blog_db.view_posts.hikeStats</code>.
     */
    public void setHikestats(HikeStats value) {
        set(11, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.hikeStats</code>.
     */
    public HikeStats getHikestats() {
        return (HikeStats) get(11);
    }

    /**
     * Setter for <code>blog_db.view_posts.hikeRating</code>.
     */
    public void setHikerating(HikeRating value) {
        set(12, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.hikeRating</code>.
     */
    public HikeRating getHikerating() {
        return (HikeRating) get(12);
    }

    /**
     * Setter for <code>blog_db.view_posts.videos</code>.
     */
    public void setVideos(String[] value) {
        set(13, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.videos</code>.
     */
    public String[] getVideos() {
        return (String[]) get(13);
    }

    /**
     * Setter for <code>blog_db.view_posts.story_ids</code>.
     */
    public void setStoryIds(Integer[] value) {
        set(14, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.story_ids</code>.
     */
    public Integer[] getStoryIds() {
        return (Integer[]) get(14);
    }

    /**
     * Setter for <code>blog_db.view_posts.images</code>.
     */
    public void setImages(PostImage[] value) {
        set(15, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.images</code>.
     */
    public PostImage[] getImages() {
        return (PostImage[]) get(15);
    }

    /**
     * Setter for <code>blog_db.view_posts.sites</code>.
     */
    public void setSites(PostSite[] value) {
        set(16, value);
    }

    /**
     * Getter for <code>blog_db.view_posts.sites</code>.
     */
    public PostSite[] getSites() {
        return (PostSite[]) get(16);
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, PostsType, String, String, String, Boolean, Integer, Timestamp, Timestamp, PostHill[], PostPerson[], HikeStats, HikeRating, String[], Integer[], PostImage[], PostSite[]> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, PostsType, String, String, String, Boolean, Integer, Timestamp, Timestamp, PostHill[], PostPerson[], HikeStats, HikeRating, String[], Integer[], PostImage[], PostSite[]> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewPosts.VIEW_POSTS.POST_ID;
    }

    @Override
    public Field<PostsType> field2() {
        return ViewPosts.VIEW_POSTS.POST_TYPE;
    }

    @Override
    public Field<String> field3() {
        return ViewPosts.VIEW_POSTS.POST_TITLE;
    }

    @Override
    public Field<String> field4() {
        return ViewPosts.VIEW_POSTS.POST_CONTENT;
    }

    @Override
    public Field<String> field5() {
        return ViewPosts.VIEW_POSTS.POST_MARKDOWN;
    }

    @Override
    public Field<Boolean> field6() {
        return ViewPosts.VIEW_POSTS.POST_VISIBLE;
    }

    @Override
    public Field<Integer> field7() {
        return ViewPosts.VIEW_POSTS.POST_VIEW_COUNT;
    }

    @Override
    public Field<Timestamp> field8() {
        return ViewPosts.VIEW_POSTS.POST_START_DATE;
    }

    @Override
    public Field<Timestamp> field9() {
        return ViewPosts.VIEW_POSTS.POST_END_DATE;
    }

    @Override
    public Field<PostHill[]> field10() {
        return ViewPosts.VIEW_POSTS.HILLS;
    }

    @Override
    public Field<PostPerson[]> field11() {
        return ViewPosts.VIEW_POSTS.PEOPLE;
    }

    @Override
    public Field<HikeStats> field12() {
        return ViewPosts.VIEW_POSTS.HIKESTATS;
    }

    @Override
    public Field<HikeRating> field13() {
        return ViewPosts.VIEW_POSTS.HIKERATING;
    }

    @Override
    public Field<String[]> field14() {
        return ViewPosts.VIEW_POSTS.VIDEOS;
    }

    @Override
    public Field<Integer[]> field15() {
        return ViewPosts.VIEW_POSTS.STORY_IDS;
    }

    @Override
    public Field<PostImage[]> field16() {
        return ViewPosts.VIEW_POSTS.IMAGES;
    }

    @Override
    public Field<PostSite[]> field17() {
        return ViewPosts.VIEW_POSTS.SITES;
    }

    @Override
    public Integer component1() {
        return getPostId();
    }

    @Override
    public PostsType component2() {
        return getPostType();
    }

    @Override
    public String component3() {
        return getPostTitle();
    }

    @Override
    public String component4() {
        return getPostContent();
    }

    @Override
    public String component5() {
        return getPostMarkdown();
    }

    @Override
    public Boolean component6() {
        return getPostVisible();
    }

    @Override
    public Integer component7() {
        return getPostViewCount();
    }

    @Override
    public Timestamp component8() {
        return getPostStartDate();
    }

    @Override
    public Timestamp component9() {
        return getPostEndDate();
    }

    @Override
    public PostHill[] component10() {
        return getHills();
    }

    @Override
    public PostPerson[] component11() {
        return getPeople();
    }

    @Override
    public HikeStats component12() {
        return getHikestats();
    }

    @Override
    public HikeRating component13() {
        return getHikerating();
    }

    @Override
    public String[] component14() {
        return getVideos();
    }

    @Override
    public Integer[] component15() {
        return getStoryIds();
    }

    @Override
    public PostImage[] component16() {
        return getImages();
    }

    @Override
    public PostSite[] component17() {
        return getSites();
    }

    @Override
    public Integer value1() {
        return getPostId();
    }

    @Override
    public PostsType value2() {
        return getPostType();
    }

    @Override
    public String value3() {
        return getPostTitle();
    }

    @Override
    public String value4() {
        return getPostContent();
    }

    @Override
    public String value5() {
        return getPostMarkdown();
    }

    @Override
    public Boolean value6() {
        return getPostVisible();
    }

    @Override
    public Integer value7() {
        return getPostViewCount();
    }

    @Override
    public Timestamp value8() {
        return getPostStartDate();
    }

    @Override
    public Timestamp value9() {
        return getPostEndDate();
    }

    @Override
    public PostHill[] value10() {
        return getHills();
    }

    @Override
    public PostPerson[] value11() {
        return getPeople();
    }

    @Override
    public HikeStats value12() {
        return getHikestats();
    }

    @Override
    public HikeRating value13() {
        return getHikerating();
    }

    @Override
    public String[] value14() {
        return getVideos();
    }

    @Override
    public Integer[] value15() {
        return getStoryIds();
    }

    @Override
    public PostImage[] value16() {
        return getImages();
    }

    @Override
    public PostSite[] value17() {
        return getSites();
    }

    @Override
    public ViewPostsRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    @Override
    public ViewPostsRecord value2(PostsType value) {
        setPostType(value);
        return this;
    }

    @Override
    public ViewPostsRecord value3(String value) {
        setPostTitle(value);
        return this;
    }

    @Override
    public ViewPostsRecord value4(String value) {
        setPostContent(value);
        return this;
    }

    @Override
    public ViewPostsRecord value5(String value) {
        setPostMarkdown(value);
        return this;
    }

    @Override
    public ViewPostsRecord value6(Boolean value) {
        setPostVisible(value);
        return this;
    }

    @Override
    public ViewPostsRecord value7(Integer value) {
        setPostViewCount(value);
        return this;
    }

    @Override
    public ViewPostsRecord value8(Timestamp value) {
        setPostStartDate(value);
        return this;
    }

    @Override
    public ViewPostsRecord value9(Timestamp value) {
        setPostEndDate(value);
        return this;
    }

    @Override
    public ViewPostsRecord value10(PostHill[] value) {
        setHills(value);
        return this;
    }

    @Override
    public ViewPostsRecord value11(PostPerson[] value) {
        setPeople(value);
        return this;
    }

    @Override
    public ViewPostsRecord value12(HikeStats value) {
        setHikestats(value);
        return this;
    }

    @Override
    public ViewPostsRecord value13(HikeRating value) {
        setHikerating(value);
        return this;
    }

    @Override
    public ViewPostsRecord value14(String[] value) {
        setVideos(value);
        return this;
    }

    @Override
    public ViewPostsRecord value15(Integer[] value) {
        setStoryIds(value);
        return this;
    }

    @Override
    public ViewPostsRecord value16(PostImage[] value) {
        setImages(value);
        return this;
    }

    @Override
    public ViewPostsRecord value17(PostSite[] value) {
        setSites(value);
        return this;
    }

    @Override
    public ViewPostsRecord values(Integer value1, PostsType value2, String value3, String value4, String value5, Boolean value6, Integer value7, Timestamp value8, Timestamp value9, PostHill[] value10, PostPerson[] value11, HikeStats value12, HikeRating value13, String[] value14, Integer[] value15, PostImage[] value16, PostSite[] value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewPostsRecord
     */
    public ViewPostsRecord() {
        super(ViewPosts.VIEW_POSTS);
    }

    /**
     * Create a detached, initialised ViewPostsRecord
     */
    public ViewPostsRecord(Integer postId, PostsType postType, String postTitle, String postContent, String postMarkdown, Boolean postVisible, Integer postViewCount, Timestamp postStartDate, Timestamp postEndDate, PostHill[] hills, PostPerson[] people, HikeStats hikestats, HikeRating hikerating, String[] videos, Integer[] storyIds, PostImage[] images, PostSite[] sites) {
        super(ViewPosts.VIEW_POSTS);

        setPostId(postId);
        setPostType(postType);
        setPostTitle(postTitle);
        setPostContent(postContent);
        setPostMarkdown(postMarkdown);
        setPostVisible(postVisible);
        setPostViewCount(postViewCount);
        setPostStartDate(postStartDate);
        setPostEndDate(postEndDate);
        setHills(hills);
        setPeople(people);
        setHikestats(hikestats);
        setHikerating(hikerating);
        setVideos(videos);
        setStoryIds(storyIds);
        setImages(images);
        setSites(sites);
    }

    /**
     * Create a detached, initialised ViewPostsRecord
     */
    public ViewPostsRecord(blog.raubach.database.codegen.tables.pojos.ViewPosts value) {
        super(ViewPosts.VIEW_POSTS);

        if (value != null) {
            setPostId(value.getPostId());
            setPostType(value.getPostType());
            setPostTitle(value.getPostTitle());
            setPostContent(value.getPostContent());
            setPostMarkdown(value.getPostMarkdown());
            setPostVisible(value.getPostVisible());
            setPostViewCount(value.getPostViewCount());
            setPostStartDate(value.getPostStartDate());
            setPostEndDate(value.getPostEndDate());
            setHills(value.getHills());
            setPeople(value.getPeople());
            setHikestats(value.getHikestats());
            setHikerating(value.getHikerating());
            setVideos(value.getVideos());
            setStoryIds(value.getStoryIds());
            setImages(value.getImages());
            setSites(value.getSites());
        }
    }
    // @formatter:on
}
