/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.enums.HillsType;
import blog.raubach.database.codegen.tables.ViewHills;
import blog.raubach.pojo.MiniPost;
import blog.raubach.pojo.view.PostPerson;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewHillsRecord extends TableRecordImpl<ViewHillsRecord> implements Record10<Integer, String, HillsType, String, String, Double, Double, Double, MiniPost[], PostPerson[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.view_hills.hill_id</code>.
     */
    public void setHillId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_id</code>.
     */
    public Integer getHillId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_name</code>.
     */
    public void setHillName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_name</code>.
     */
    public String getHillName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_type</code>.
     */
    public void setHillType(HillsType value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_type</code>.
     */
    public HillsType getHillType() {
        return (HillsType) get(2);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_region</code>.
     */
    public void setHillRegion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_region</code>.
     */
    public String getHillRegion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_url</code>.
     */
    public void setHillUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_url</code>.
     */
    public String getHillUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_latitude</code>.
     */
    public void setHillLatitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_latitude</code>.
     */
    public Double getHillLatitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_longitude</code>.
     */
    public void setHillLongitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_longitude</code>.
     */
    public Double getHillLongitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_elevation</code>.
     */
    public void setHillElevation(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_elevation</code>.
     */
    public Double getHillElevation() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>blog_db.view_hills.posts</code>.
     */
    public void setPosts(MiniPost[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.posts</code>.
     */
    public MiniPost[] getPosts() {
        return (MiniPost[]) get(8);
    }

    /**
     * Setter for <code>blog_db.view_hills.people</code>.
     */
    public void setPeople(PostPerson[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>blog_db.view_hills.people</code>.
     */
    public PostPerson[] getPeople() {
        return (PostPerson[]) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, HillsType, String, String, Double, Double, Double, MiniPost[], PostPerson[]> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, HillsType, String, String, Double, Double, Double, MiniPost[], PostPerson[]> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewHills.VIEW_HILLS.HILL_ID;
    }

    @Override
    public Field<String> field2() {
        return ViewHills.VIEW_HILLS.HILL_NAME;
    }

    @Override
    public Field<HillsType> field3() {
        return ViewHills.VIEW_HILLS.HILL_TYPE;
    }

    @Override
    public Field<String> field4() {
        return ViewHills.VIEW_HILLS.HILL_REGION;
    }

    @Override
    public Field<String> field5() {
        return ViewHills.VIEW_HILLS.HILL_URL;
    }

    @Override
    public Field<Double> field6() {
        return ViewHills.VIEW_HILLS.HILL_LATITUDE;
    }

    @Override
    public Field<Double> field7() {
        return ViewHills.VIEW_HILLS.HILL_LONGITUDE;
    }

    @Override
    public Field<Double> field8() {
        return ViewHills.VIEW_HILLS.HILL_ELEVATION;
    }

    @Override
    public Field<MiniPost[]> field9() {
        return ViewHills.VIEW_HILLS.POSTS;
    }

    @Override
    public Field<PostPerson[]> field10() {
        return ViewHills.VIEW_HILLS.PEOPLE;
    }

    @Override
    public Integer component1() {
        return getHillId();
    }

    @Override
    public String component2() {
        return getHillName();
    }

    @Override
    public HillsType component3() {
        return getHillType();
    }

    @Override
    public String component4() {
        return getHillRegion();
    }

    @Override
    public String component5() {
        return getHillUrl();
    }

    @Override
    public Double component6() {
        return getHillLatitude();
    }

    @Override
    public Double component7() {
        return getHillLongitude();
    }

    @Override
    public Double component8() {
        return getHillElevation();
    }

    @Override
    public MiniPost[] component9() {
        return getPosts();
    }

    @Override
    public PostPerson[] component10() {
        return getPeople();
    }

    @Override
    public Integer value1() {
        return getHillId();
    }

    @Override
    public String value2() {
        return getHillName();
    }

    @Override
    public HillsType value3() {
        return getHillType();
    }

    @Override
    public String value4() {
        return getHillRegion();
    }

    @Override
    public String value5() {
        return getHillUrl();
    }

    @Override
    public Double value6() {
        return getHillLatitude();
    }

    @Override
    public Double value7() {
        return getHillLongitude();
    }

    @Override
    public Double value8() {
        return getHillElevation();
    }

    @Override
    public MiniPost[] value9() {
        return getPosts();
    }

    @Override
    public PostPerson[] value10() {
        return getPeople();
    }

    @Override
    public ViewHillsRecord value1(Integer value) {
        setHillId(value);
        return this;
    }

    @Override
    public ViewHillsRecord value2(String value) {
        setHillName(value);
        return this;
    }

    @Override
    public ViewHillsRecord value3(HillsType value) {
        setHillType(value);
        return this;
    }

    @Override
    public ViewHillsRecord value4(String value) {
        setHillRegion(value);
        return this;
    }

    @Override
    public ViewHillsRecord value5(String value) {
        setHillUrl(value);
        return this;
    }

    @Override
    public ViewHillsRecord value6(Double value) {
        setHillLatitude(value);
        return this;
    }

    @Override
    public ViewHillsRecord value7(Double value) {
        setHillLongitude(value);
        return this;
    }

    @Override
    public ViewHillsRecord value8(Double value) {
        setHillElevation(value);
        return this;
    }

    @Override
    public ViewHillsRecord value9(MiniPost[] value) {
        setPosts(value);
        return this;
    }

    @Override
    public ViewHillsRecord value10(PostPerson[] value) {
        setPeople(value);
        return this;
    }

    @Override
    public ViewHillsRecord values(Integer value1, String value2, HillsType value3, String value4, String value5, Double value6, Double value7, Double value8, MiniPost[] value9, PostPerson[] value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewHillsRecord
     */
    public ViewHillsRecord() {
        super(ViewHills.VIEW_HILLS);
    }

    /**
     * Create a detached, initialised ViewHillsRecord
     */
    public ViewHillsRecord(Integer hillId, String hillName, HillsType hillType, String hillRegion, String hillUrl, Double hillLatitude, Double hillLongitude, Double hillElevation, MiniPost[] posts, PostPerson[] people) {
        super(ViewHills.VIEW_HILLS);

        setHillId(hillId);
        setHillName(hillName);
        setHillType(hillType);
        setHillRegion(hillRegion);
        setHillUrl(hillUrl);
        setHillLatitude(hillLatitude);
        setHillLongitude(hillLongitude);
        setHillElevation(hillElevation);
        setPosts(posts);
        setPeople(people);
    }

    /**
     * Create a detached, initialised ViewHillsRecord
     */
    public ViewHillsRecord(blog.raubach.database.codegen.tables.pojos.ViewHills value) {
        super(ViewHills.VIEW_HILLS);

        if (value != null) {
            setHillId(value.getHillId());
            setHillName(value.getHillName());
            setHillType(value.getHillType());
            setHillRegion(value.getHillRegion());
            setHillUrl(value.getHillUrl());
            setHillLatitude(value.getHillLatitude());
            setHillLongitude(value.getHillLongitude());
            setHillElevation(value.getHillElevation());
            setPosts(value.getPosts());
            setPeople(value.getPeople());
        }
    }
    // @formatter:on
}
