/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.records;


import blog.raubach.database.codegen.enums.PostsitesGroundtype;
import blog.raubach.database.codegen.enums.SitesSitetype;
import blog.raubach.database.codegen.tables.ViewSites;
import blog.raubach.pojo.SiteFacilities;
import blog.raubach.pojo.SiteRating;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSitesRecord extends TableRecordImpl<ViewSitesRecord> implements Record13<Integer, String, String, SitesSitetype, Double, Double, Double, SiteRating, SiteFacilities, Timestamp, Timestamp, PostsitesGroundtype[], Integer[]> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog_db.view_sites.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.view_sites.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.view_sites.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blog_db.view_sites.sitetype</code>.
     */
    public void setSitetype(SitesSitetype value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.sitetype</code>.
     */
    public SitesSitetype getSitetype() {
        return (SitesSitetype) get(3);
    }

    /**
     * Setter for <code>blog_db.view_sites.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>blog_db.view_sites.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>blog_db.view_sites.elevation</code>.
     */
    public void setElevation(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.elevation</code>.
     */
    public Double getElevation() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>blog_db.view_sites.rating</code>.
     */
    public void setRating(SiteRating value) {
        set(7, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.rating</code>.
     */
    public SiteRating getRating() {
        return (SiteRating) get(7);
    }

    /**
     * Setter for <code>blog_db.view_sites.facilities</code>.
     */
    public void setFacilities(SiteFacilities value) {
        set(8, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.facilities</code>.
     */
    public SiteFacilities getFacilities() {
        return (SiteFacilities) get(8);
    }

    /**
     * Setter for <code>blog_db.view_sites.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>blog_db.view_sites.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>blog_db.view_sites.groundtypes</code>.
     */
    public void setGroundtypes(PostsitesGroundtype[] value) {
        set(11, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.groundtypes</code>.
     */
    public PostsitesGroundtype[] getGroundtypes() {
        return (PostsitesGroundtype[]) get(11);
    }

    /**
     * Setter for <code>blog_db.view_sites.post_ids</code>.
     */
    public void setPostIds(Integer[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>blog_db.view_sites.post_ids</code>.
     */
    public Integer[] getPostIds() {
        return (Integer[]) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, SitesSitetype, Double, Double, Double, SiteRating, SiteFacilities, Timestamp, Timestamp, PostsitesGroundtype[], Integer[]> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, String, SitesSitetype, Double, Double, Double, SiteRating, SiteFacilities, Timestamp, Timestamp, PostsitesGroundtype[], Integer[]> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ViewSites.VIEW_SITES.ID;
    }

    @Override
    public Field<String> field2() {
        return ViewSites.VIEW_SITES.NAME;
    }

    @Override
    public Field<String> field3() {
        return ViewSites.VIEW_SITES.DESCRIPTION;
    }

    @Override
    public Field<SitesSitetype> field4() {
        return ViewSites.VIEW_SITES.SITETYPE;
    }

    @Override
    public Field<Double> field5() {
        return ViewSites.VIEW_SITES.LATITUDE;
    }

    @Override
    public Field<Double> field6() {
        return ViewSites.VIEW_SITES.LONGITUDE;
    }

    @Override
    public Field<Double> field7() {
        return ViewSites.VIEW_SITES.ELEVATION;
    }

    @Override
    public Field<SiteRating> field8() {
        return ViewSites.VIEW_SITES.RATING;
    }

    @Override
    public Field<SiteFacilities> field9() {
        return ViewSites.VIEW_SITES.FACILITIES;
    }

    @Override
    public Field<Timestamp> field10() {
        return ViewSites.VIEW_SITES.CREATED_ON;
    }

    @Override
    public Field<Timestamp> field11() {
        return ViewSites.VIEW_SITES.UPDATED_ON;
    }

    @Override
    public Field<PostsitesGroundtype[]> field12() {
        return ViewSites.VIEW_SITES.GROUNDTYPES;
    }

    @Override
    public Field<Integer[]> field13() {
        return ViewSites.VIEW_SITES.POST_IDS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public SitesSitetype component4() {
        return getSitetype();
    }

    @Override
    public Double component5() {
        return getLatitude();
    }

    @Override
    public Double component6() {
        return getLongitude();
    }

    @Override
    public Double component7() {
        return getElevation();
    }

    @Override
    public SiteRating component8() {
        return getRating();
    }

    @Override
    public SiteFacilities component9() {
        return getFacilities();
    }

    @Override
    public Timestamp component10() {
        return getCreatedOn();
    }

    @Override
    public Timestamp component11() {
        return getUpdatedOn();
    }

    @Override
    public PostsitesGroundtype[] component12() {
        return getGroundtypes();
    }

    @Override
    public Integer[] component13() {
        return getPostIds();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public SitesSitetype value4() {
        return getSitetype();
    }

    @Override
    public Double value5() {
        return getLatitude();
    }

    @Override
    public Double value6() {
        return getLongitude();
    }

    @Override
    public Double value7() {
        return getElevation();
    }

    @Override
    public SiteRating value8() {
        return getRating();
    }

    @Override
    public SiteFacilities value9() {
        return getFacilities();
    }

    @Override
    public Timestamp value10() {
        return getCreatedOn();
    }

    @Override
    public Timestamp value11() {
        return getUpdatedOn();
    }

    @Override
    public PostsitesGroundtype[] value12() {
        return getGroundtypes();
    }

    @Override
    public Integer[] value13() {
        return getPostIds();
    }

    @Override
    public ViewSitesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ViewSitesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ViewSitesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ViewSitesRecord value4(SitesSitetype value) {
        setSitetype(value);
        return this;
    }

    @Override
    public ViewSitesRecord value5(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public ViewSitesRecord value6(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public ViewSitesRecord value7(Double value) {
        setElevation(value);
        return this;
    }

    @Override
    public ViewSitesRecord value8(SiteRating value) {
        setRating(value);
        return this;
    }

    @Override
    public ViewSitesRecord value9(SiteFacilities value) {
        setFacilities(value);
        return this;
    }

    @Override
    public ViewSitesRecord value10(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ViewSitesRecord value11(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ViewSitesRecord value12(PostsitesGroundtype[] value) {
        setGroundtypes(value);
        return this;
    }

    @Override
    public ViewSitesRecord value13(Integer[] value) {
        setPostIds(value);
        return this;
    }

    @Override
    public ViewSitesRecord values(Integer value1, String value2, String value3, SitesSitetype value4, Double value5, Double value6, Double value7, SiteRating value8, SiteFacilities value9, Timestamp value10, Timestamp value11, PostsitesGroundtype[] value12, Integer[] value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewSitesRecord
     */
    public ViewSitesRecord() {
        super(ViewSites.VIEW_SITES);
    }

    /**
     * Create a detached, initialised ViewSitesRecord
     */
    public ViewSitesRecord(Integer id, String name, String description, SitesSitetype sitetype, Double latitude, Double longitude, Double elevation, SiteRating rating, SiteFacilities facilities, Timestamp createdOn, Timestamp updatedOn, PostsitesGroundtype[] groundtypes, Integer[] postIds) {
        super(ViewSites.VIEW_SITES);

        setId(id);
        setName(name);
        setDescription(description);
        setSitetype(sitetype);
        setLatitude(latitude);
        setLongitude(longitude);
        setElevation(elevation);
        setRating(rating);
        setFacilities(facilities);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
        setGroundtypes(groundtypes);
        setPostIds(postIds);
    }

    /**
     * Create a detached, initialised ViewSitesRecord
     */
    public ViewSitesRecord(blog.raubach.database.codegen.tables.pojos.ViewSites value) {
        super(ViewSites.VIEW_SITES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDescription(value.getDescription());
            setSitetype(value.getSitetype());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setElevation(value.getElevation());
            setRating(value.getRating());
            setFacilities(value.getFacilities());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
            setGroundtypes(value.getGroundtypes());
            setPostIds(value.getPostIds());
        }
    }
    // @formatter:on
}
