/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hikestats implements Serializable {

    private static final long serialVersionUID = -1941373951;

    private Integer   postId;
    private Integer   duration;
    private Double    distance;
    private Double    ascent;
    private String    gpxPath;
    private String    elevationProfilePath;
    private String    timeDistanceProfilePath;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Hikestats() {}

    public Hikestats(Hikestats value) {
        this.postId = value.postId;
        this.duration = value.duration;
        this.distance = value.distance;
        this.ascent = value.ascent;
        this.gpxPath = value.gpxPath;
        this.elevationProfilePath = value.elevationProfilePath;
        this.timeDistanceProfilePath = value.timeDistanceProfilePath;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Hikestats(
        Integer   postId,
        Integer   duration,
        Double    distance,
        Double    ascent,
        String    gpxPath,
        String    elevationProfilePath,
        String    timeDistanceProfilePath,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.postId = postId;
        this.duration = duration;
        this.distance = distance;
        this.ascent = ascent;
        this.gpxPath = gpxPath;
        this.elevationProfilePath = elevationProfilePath;
        this.timeDistanceProfilePath = timeDistanceProfilePath;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Double getDistance() {
        return this.distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public Double getAscent() {
        return this.ascent;
    }

    public void setAscent(Double ascent) {
        this.ascent = ascent;
    }

    public String getGpxPath() {
        return this.gpxPath;
    }

    public void setGpxPath(String gpxPath) {
        this.gpxPath = gpxPath;
    }

    public String getElevationProfilePath() {
        return this.elevationProfilePath;
    }

    public void setElevationProfilePath(String elevationProfilePath) {
        this.elevationProfilePath = elevationProfilePath;
    }

    public String getTimeDistanceProfilePath() {
        return this.timeDistanceProfilePath;
    }

    public void setTimeDistanceProfilePath(String timeDistanceProfilePath) {
        this.timeDistanceProfilePath = timeDistanceProfilePath;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Hikestats (");

        sb.append(postId);
        sb.append(", ").append(duration);
        sb.append(", ").append(distance);
        sb.append(", ").append(ascent);
        sb.append(", ").append(gpxPath);
        sb.append(", ").append(elevationProfilePath);
        sb.append(", ").append(timeDistanceProfilePath);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
