/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hikeratings implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer postId;
    private Short   weather;
    private Short   path;
    private Short   view;

    public Hikeratings() {}

    public Hikeratings(Hikeratings value) {
        this.postId = value.postId;
        this.weather = value.weather;
        this.path = value.path;
        this.view = value.view;
    }

    public Hikeratings(
        Integer postId,
        Short   weather,
        Short   path,
        Short   view
    ) {
        this.postId = postId;
        this.weather = weather;
        this.path = path;
        this.view = view;
    }

    /**
     * Getter for <code>blog_db.hikeratings.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.hikeratings.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.hikeratings.weather</code>.
     */
    public Short getWeather() {
        return this.weather;
    }

    /**
     * Setter for <code>blog_db.hikeratings.weather</code>.
     */
    public void setWeather(Short weather) {
        this.weather = weather;
    }

    /**
     * Getter for <code>blog_db.hikeratings.path</code>.
     */
    public Short getPath() {
        return this.path;
    }

    /**
     * Setter for <code>blog_db.hikeratings.path</code>.
     */
    public void setPath(Short path) {
        this.path = path;
    }

    /**
     * Getter for <code>blog_db.hikeratings.view</code>.
     */
    public Short getView() {
        return this.view;
    }

    /**
     * Setter for <code>blog_db.hikeratings.view</code>.
     */
    public void setView(Short view) {
        this.view = view;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Hikeratings (");

        sb.append(postId);
        sb.append(", ").append(weather);
        sb.append(", ").append(path);
        sb.append(", ").append(view);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
