/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hikeratings implements Serializable {

    private static final long serialVersionUID = 291367536;

    private Integer postId;
    private Short   weather;
    private Short   path;
    private Short   view;

    public Hikeratings() {}

    public Hikeratings(Hikeratings value) {
        this.postId = value.postId;
        this.weather = value.weather;
        this.path = value.path;
        this.view = value.view;
    }

    public Hikeratings(
        Integer postId,
        Short   weather,
        Short   path,
        Short   view
    ) {
        this.postId = postId;
        this.weather = weather;
        this.path = path;
        this.view = view;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public Short getWeather() {
        return this.weather;
    }

    public void setWeather(Short weather) {
        this.weather = weather;
    }

    public Short getPath() {
        return this.path;
    }

    public void setPath(Short path) {
        this.path = path;
    }

    public Short getView() {
        return this.view;
    }

    public void setView(Short view) {
        this.view = view;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Hikeratings (");

        sb.append(postId);
        sb.append(", ").append(weather);
        sb.append(", ").append(path);
        sb.append(", ").append(view);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
