/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HillIndividuals implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   hillId;
    private Integer   individualId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public HillIndividuals() {}

    public HillIndividuals(HillIndividuals value) {
        this.id = value.id;
        this.hillId = value.hillId;
        this.individualId = value.individualId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public HillIndividuals(
        Integer   id,
        Integer   hillId,
        Integer   individualId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.hillId = hillId;
        this.individualId = individualId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>blog_db.hill_individuals.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>blog_db.hill_individuals.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>blog_db.hill_individuals.hill_id</code>.
     */
    public Integer getHillId() {
        return this.hillId;
    }

    /**
     * Setter for <code>blog_db.hill_individuals.hill_id</code>.
     */
    public void setHillId(Integer hillId) {
        this.hillId = hillId;
    }

    /**
     * Getter for <code>blog_db.hill_individuals.individual_id</code>.
     */
    public Integer getIndividualId() {
        return this.individualId;
    }

    /**
     * Setter for <code>blog_db.hill_individuals.individual_id</code>.
     */
    public void setIndividualId(Integer individualId) {
        this.individualId = individualId;
    }

    /**
     * Getter for <code>blog_db.hill_individuals.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>blog_db.hill_individuals.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>blog_db.hill_individuals.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>blog_db.hill_individuals.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HillIndividuals (");

        sb.append(id);
        sb.append(", ").append(hillId);
        sb.append(", ").append(individualId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
