/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer imageId;
    private String  imagePath;
    private Integer postId;
    private Boolean isPrimary;
    private String  description;

    public ImageDetails() {}

    public ImageDetails(ImageDetails value) {
        this.imageId = value.imageId;
        this.imagePath = value.imagePath;
        this.postId = value.postId;
        this.isPrimary = value.isPrimary;
        this.description = value.description;
    }

    public ImageDetails(
        Integer imageId,
        String  imagePath,
        Integer postId,
        Boolean isPrimary,
        String  description
    ) {
        this.imageId = imageId;
        this.imagePath = imagePath;
        this.postId = postId;
        this.isPrimary = isPrimary;
        this.description = description;
    }

    /**
     * Getter for <code>blog_db.image_details.image_id</code>.
     */
    public Integer getImageId() {
        return this.imageId;
    }

    /**
     * Setter for <code>blog_db.image_details.image_id</code>.
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * Getter for <code>blog_db.image_details.image_path</code>.
     */
    public String getImagePath() {
        return this.imagePath;
    }

    /**
     * Setter for <code>blog_db.image_details.image_path</code>.
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * Getter for <code>blog_db.image_details.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.image_details.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.image_details.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }

    /**
     * Setter for <code>blog_db.image_details.is_primary</code>.
     */
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }

    /**
     * Getter for <code>blog_db.image_details.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>blog_db.image_details.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImageDetails (");

        sb.append(imageId);
        sb.append(", ").append(imagePath);
        sb.append(", ").append(postId);
        sb.append(", ").append(isPrimary);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
