/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostIndividuals implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   postId;
    private Integer   individualId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public PostIndividuals() {}

    public PostIndividuals(PostIndividuals value) {
        this.id = value.id;
        this.postId = value.postId;
        this.individualId = value.individualId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public PostIndividuals(
        Integer   id,
        Integer   postId,
        Integer   individualId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.postId = postId;
        this.individualId = individualId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>blog_db.post_individuals.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>blog_db.post_individuals.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>blog_db.post_individuals.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.post_individuals.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.post_individuals.individual_id</code>.
     */
    public Integer getIndividualId() {
        return this.individualId;
    }

    /**
     * Setter for <code>blog_db.post_individuals.individual_id</code>.
     */
    public void setIndividualId(Integer individualId) {
        this.individualId = individualId;
    }

    /**
     * Getter for <code>blog_db.post_individuals.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>blog_db.post_individuals.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>blog_db.post_individuals.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>blog_db.post_individuals.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PostIndividuals (");

        sb.append(id);
        sb.append(", ").append(postId);
        sb.append(", ").append(individualId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
