/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postvideos implements Serializable {

    private static final long serialVersionUID = -1875427441;

    private Integer   postId;
    private String    videoPath;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Postvideos() {}

    public Postvideos(Postvideos value) {
        this.postId = value.postId;
        this.videoPath = value.videoPath;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Postvideos(
        Integer   postId,
        String    videoPath,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.postId = postId;
        this.videoPath = videoPath;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    public String getVideoPath() {
        return this.videoPath;
    }

    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Postvideos (");

        sb.append(postId);
        sb.append(", ").append(videoPath);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
