/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postsites implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer postId;
    private Integer siteId;

    public Postsites() {}

    public Postsites(Postsites value) {
        this.postId = value.postId;
        this.siteId = value.siteId;
    }

    public Postsites(
        Integer postId,
        Integer siteId
    ) {
        this.postId = postId;
        this.siteId = siteId;
    }

    /**
     * Getter for <code>blog_db.postsites.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.postsites.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.postsites.site_id</code>.
     */
    public Integer getSiteId() {
        return this.siteId;
    }

    /**
     * Setter for <code>blog_db.postsites.site_id</code>.
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Postsites (");

        sb.append(postId);
        sb.append(", ").append(siteId);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
