/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postusers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer postId;
    private Integer userId;

    public Postusers() {}

    public Postusers(Postusers value) {
        this.postId = value.postId;
        this.userId = value.userId;
    }

    public Postusers(
        Integer postId,
        Integer userId
    ) {
        this.postId = postId;
        this.userId = userId;
    }

    /**
     * Getter for <code>blog_db.postusers.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.postusers.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.postusers.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>blog_db.postusers.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Postusers (");

        sb.append(postId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
