/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postvideos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   postId;
    private String    videoPath;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Postvideos() {}

    public Postvideos(Postvideos value) {
        this.postId = value.postId;
        this.videoPath = value.videoPath;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Postvideos(
        Integer   postId,
        String    videoPath,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.postId = postId;
        this.videoPath = videoPath;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>blog_db.postvideos.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.postvideos.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.postvideos.video_path</code>.
     */
    public String getVideoPath() {
        return this.videoPath;
    }

    /**
     * Setter for <code>blog_db.postvideos.video_path</code>.
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath;
    }

    /**
     * Getter for <code>blog_db.postvideos.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>blog_db.postvideos.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>blog_db.postvideos.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>blog_db.postvideos.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Postvideos (");

        sb.append(postId);
        sb.append(", ").append(videoPath);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
