/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postimages implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer postId;
    private Integer imageId;
    private Boolean isPrimary;
    private String  description;

    public Postimages() {}

    public Postimages(Postimages value) {
        this.postId = value.postId;
        this.imageId = value.imageId;
        this.isPrimary = value.isPrimary;
        this.description = value.description;
    }

    public Postimages(
        Integer postId,
        Integer imageId,
        Boolean isPrimary,
        String  description
    ) {
        this.postId = postId;
        this.imageId = imageId;
        this.isPrimary = isPrimary;
        this.description = description;
    }

    /**
     * Getter for <code>blog_db.postimages.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.postimages.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.postimages.image_id</code>.
     */
    public Integer getImageId() {
        return this.imageId;
    }

    /**
     * Setter for <code>blog_db.postimages.image_id</code>.
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * Getter for <code>blog_db.postimages.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }

    /**
     * Setter for <code>blog_db.postimages.is_primary</code>.
     */
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }

    /**
     * Getter for <code>blog_db.postimages.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>blog_db.postimages.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Postimages (");

        sb.append(postId);
        sb.append(", ").append(imageId);
        sb.append(", ").append(isPrimary);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
