/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relationships implements Serializable {

    private static final long serialVersionUID = 1613645911;

    private Integer   postAId;
    private Integer   postBId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Relationships() {}

    public Relationships(Relationships value) {
        this.postAId = value.postAId;
        this.postBId = value.postBId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Relationships(
        Integer   postAId,
        Integer   postBId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.postAId = postAId;
        this.postBId = postBId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getPostAId() {
        return this.postAId;
    }

    public void setPostAId(Integer postAId) {
        this.postAId = postAId;
    }

    public Integer getPostBId() {
        return this.postBId;
    }

    public void setPostBId(Integer postBId) {
        this.postBId = postBId;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Relationships (");

        sb.append(postAId);
        sb.append(", ").append(postBId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
