/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relationships implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   postAId;
    private Integer   postBId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Relationships() {}

    public Relationships(Relationships value) {
        this.postAId = value.postAId;
        this.postBId = value.postBId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Relationships(
        Integer   postAId,
        Integer   postBId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.postAId = postAId;
        this.postBId = postBId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>blog_db.relationships.post_a_id</code>.
     */
    public Integer getPostAId() {
        return this.postAId;
    }

    /**
     * Setter for <code>blog_db.relationships.post_a_id</code>.
     */
    public void setPostAId(Integer postAId) {
        this.postAId = postAId;
    }

    /**
     * Getter for <code>blog_db.relationships.post_b_id</code>.
     */
    public Integer getPostBId() {
        return this.postBId;
    }

    /**
     * Setter for <code>blog_db.relationships.post_b_id</code>.
     */
    public void setPostBId(Integer postBId) {
        this.postBId = postBId;
    }

    /**
     * Getter for <code>blog_db.relationships.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>blog_db.relationships.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>blog_db.relationships.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>blog_db.relationships.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Relationships (");

        sb.append(postAId);
        sb.append(", ").append(postBId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
