/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    username;
    private String    password;
    private String    displayname;
    private byte[]    photo;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.displayname = value.displayname;
        this.photo = value.photo;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Users(
        Integer   id,
        String    username,
        String    password,
        String    displayname,
        byte[]    photo,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.displayname = displayname;
        this.photo = photo;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>blog_db.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>blog_db.users.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>blog_db.users.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>blog_db.users.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>blog_db.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>blog_db.users.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>blog_db.users.displayname</code>.
     */
    public String getDisplayname() {
        return this.displayname;
    }

    /**
     * Setter for <code>blog_db.users.displayname</code>.
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    /**
     * Getter for <code>blog_db.users.photo</code>.
     */
    public byte[] getPhoto() {
        return this.photo;
    }

    /**
     * Setter for <code>blog_db.users.photo</code>.
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    /**
     * Getter for <code>blog_db.users.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>blog_db.users.created_on</code>.
     */
    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>blog_db.users.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>blog_db.users.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(displayname);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
