/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import blog.raubach.database.codegen.enums.PostsType;
import blog.raubach.pojo.view.HikeRating;
import blog.raubach.pojo.view.HikeStats;
import blog.raubach.pojo.view.PostHill;
import blog.raubach.pojo.view.PostImage;
import blog.raubach.pojo.view.PostPerson;
import blog.raubach.pojo.view.PostSite;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewPosts implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer      postId;
    private PostsType    postType;
    private String       postTitle;
    private String       postContent;
    private String       postMarkdown;
    private Boolean      postVisible;
    private Integer      postViewCount;
    private Timestamp    postStartDate;
    private Timestamp    postEndDate;
    private PostHill[]   hills;
    private PostPerson[] people;
    private HikeStats    hikestats;
    private HikeRating   hikerating;
    private String[]     videos;
    private Integer[]    storyIds;
    private PostImage[]  images;
    private PostSite[]   sites;

    public ViewPosts() {}

    public ViewPosts(ViewPosts value) {
        this.postId = value.postId;
        this.postType = value.postType;
        this.postTitle = value.postTitle;
        this.postContent = value.postContent;
        this.postMarkdown = value.postMarkdown;
        this.postVisible = value.postVisible;
        this.postViewCount = value.postViewCount;
        this.postStartDate = value.postStartDate;
        this.postEndDate = value.postEndDate;
        this.hills = value.hills;
        this.people = value.people;
        this.hikestats = value.hikestats;
        this.hikerating = value.hikerating;
        this.videos = value.videos;
        this.storyIds = value.storyIds;
        this.images = value.images;
        this.sites = value.sites;
    }

    public ViewPosts(
        Integer      postId,
        PostsType    postType,
        String       postTitle,
        String       postContent,
        String       postMarkdown,
        Boolean      postVisible,
        Integer      postViewCount,
        Timestamp    postStartDate,
        Timestamp    postEndDate,
        PostHill[]   hills,
        PostPerson[] people,
        HikeStats    hikestats,
        HikeRating   hikerating,
        String[]     videos,
        Integer[]    storyIds,
        PostImage[]  images,
        PostSite[]   sites
    ) {
        this.postId = postId;
        this.postType = postType;
        this.postTitle = postTitle;
        this.postContent = postContent;
        this.postMarkdown = postMarkdown;
        this.postVisible = postVisible;
        this.postViewCount = postViewCount;
        this.postStartDate = postStartDate;
        this.postEndDate = postEndDate;
        this.hills = hills;
        this.people = people;
        this.hikestats = hikestats;
        this.hikerating = hikerating;
        this.videos = videos;
        this.storyIds = storyIds;
        this.images = images;
        this.sites = sites;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_id</code>.
     */
    public Integer getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_id</code>.
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_type</code>.
     */
    public PostsType getPostType() {
        return this.postType;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_type</code>.
     */
    public void setPostType(PostsType postType) {
        this.postType = postType;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_title</code>.
     */
    public String getPostTitle() {
        return this.postTitle;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_title</code>.
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_content</code>.
     */
    public String getPostContent() {
        return this.postContent;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_content</code>.
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_markdown</code>.
     */
    public String getPostMarkdown() {
        return this.postMarkdown;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_markdown</code>.
     */
    public void setPostMarkdown(String postMarkdown) {
        this.postMarkdown = postMarkdown;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_visible</code>.
     */
    public Boolean getPostVisible() {
        return this.postVisible;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_visible</code>.
     */
    public void setPostVisible(Boolean postVisible) {
        this.postVisible = postVisible;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_view_count</code>.
     */
    public Integer getPostViewCount() {
        return this.postViewCount;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_view_count</code>.
     */
    public void setPostViewCount(Integer postViewCount) {
        this.postViewCount = postViewCount;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_start_date</code>.
     */
    public Timestamp getPostStartDate() {
        return this.postStartDate;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_start_date</code>.
     */
    public void setPostStartDate(Timestamp postStartDate) {
        this.postStartDate = postStartDate;
    }

    /**
     * Getter for <code>blog_db.view_posts.post_end_date</code>.
     */
    public Timestamp getPostEndDate() {
        return this.postEndDate;
    }

    /**
     * Setter for <code>blog_db.view_posts.post_end_date</code>.
     */
    public void setPostEndDate(Timestamp postEndDate) {
        this.postEndDate = postEndDate;
    }

    /**
     * Getter for <code>blog_db.view_posts.hills</code>.
     */
    public PostHill[] getHills() {
        return this.hills;
    }

    /**
     * Setter for <code>blog_db.view_posts.hills</code>.
     */
    public void setHills(PostHill[] hills) {
        this.hills = hills;
    }

    /**
     * Getter for <code>blog_db.view_posts.people</code>.
     */
    public PostPerson[] getPeople() {
        return this.people;
    }

    /**
     * Setter for <code>blog_db.view_posts.people</code>.
     */
    public void setPeople(PostPerson[] people) {
        this.people = people;
    }

    /**
     * Getter for <code>blog_db.view_posts.hikeStats</code>.
     */
    public HikeStats getHikestats() {
        return this.hikestats;
    }

    /**
     * Setter for <code>blog_db.view_posts.hikeStats</code>.
     */
    public void setHikestats(HikeStats hikestats) {
        this.hikestats = hikestats;
    }

    /**
     * Getter for <code>blog_db.view_posts.hikeRating</code>.
     */
    public HikeRating getHikerating() {
        return this.hikerating;
    }

    /**
     * Setter for <code>blog_db.view_posts.hikeRating</code>.
     */
    public void setHikerating(HikeRating hikerating) {
        this.hikerating = hikerating;
    }

    /**
     * Getter for <code>blog_db.view_posts.videos</code>.
     */
    public String[] getVideos() {
        return this.videos;
    }

    /**
     * Setter for <code>blog_db.view_posts.videos</code>.
     */
    public void setVideos(String[] videos) {
        this.videos = videos;
    }

    /**
     * Getter for <code>blog_db.view_posts.story_ids</code>.
     */
    public Integer[] getStoryIds() {
        return this.storyIds;
    }

    /**
     * Setter for <code>blog_db.view_posts.story_ids</code>.
     */
    public void setStoryIds(Integer[] storyIds) {
        this.storyIds = storyIds;
    }

    /**
     * Getter for <code>blog_db.view_posts.images</code>.
     */
    public PostImage[] getImages() {
        return this.images;
    }

    /**
     * Setter for <code>blog_db.view_posts.images</code>.
     */
    public void setImages(PostImage[] images) {
        this.images = images;
    }

    /**
     * Getter for <code>blog_db.view_posts.sites</code>.
     */
    public PostSite[] getSites() {
        return this.sites;
    }

    /**
     * Setter for <code>blog_db.view_posts.sites</code>.
     */
    public void setSites(PostSite[] sites) {
        this.sites = sites;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewPosts (");

        sb.append(postId);
        sb.append(", ").append(postType);
        sb.append(", ").append(postTitle);
        sb.append(", ").append(postContent);
        sb.append(", ").append(postMarkdown);
        sb.append(", ").append(postVisible);
        sb.append(", ").append(postViewCount);
        sb.append(", ").append(postStartDate);
        sb.append(", ").append(postEndDate);
        sb.append(", ").append(Arrays.toString(hills));
        sb.append(", ").append(Arrays.toString(people));
        sb.append(", ").append(hikestats);
        sb.append(", ").append(hikerating);
        sb.append(", ").append(Arrays.toString(videos));
        sb.append(", ").append(Arrays.toString(storyIds));
        sb.append(", ").append(Arrays.toString(images));
        sb.append(", ").append(Arrays.toString(sites));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
