/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import blog.raubach.pojo.MiniPost;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Arrays;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewStories implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer    storyId;
    private String     storyTitle;
    private String     storyContent;
    private String     storyMarkdown;
    private Timestamp  storyStartDate;
    private MiniPost[] posts;

    public ViewStories() {}

    public ViewStories(ViewStories value) {
        this.storyId = value.storyId;
        this.storyTitle = value.storyTitle;
        this.storyContent = value.storyContent;
        this.storyMarkdown = value.storyMarkdown;
        this.storyStartDate = value.storyStartDate;
        this.posts = value.posts;
    }

    public ViewStories(
        Integer    storyId,
        String     storyTitle,
        String     storyContent,
        String     storyMarkdown,
        Timestamp  storyStartDate,
        MiniPost[] posts
    ) {
        this.storyId = storyId;
        this.storyTitle = storyTitle;
        this.storyContent = storyContent;
        this.storyMarkdown = storyMarkdown;
        this.storyStartDate = storyStartDate;
        this.posts = posts;
    }

    /**
     * Getter for <code>blog_db.view_stories.story_id</code>.
     */
    public Integer getStoryId() {
        return this.storyId;
    }

    /**
     * Setter for <code>blog_db.view_stories.story_id</code>.
     */
    public void setStoryId(Integer storyId) {
        this.storyId = storyId;
    }

    /**
     * Getter for <code>blog_db.view_stories.story_title</code>.
     */
    public String getStoryTitle() {
        return this.storyTitle;
    }

    /**
     * Setter for <code>blog_db.view_stories.story_title</code>.
     */
    public void setStoryTitle(String storyTitle) {
        this.storyTitle = storyTitle;
    }

    /**
     * Getter for <code>blog_db.view_stories.story_content</code>.
     */
    public String getStoryContent() {
        return this.storyContent;
    }

    /**
     * Setter for <code>blog_db.view_stories.story_content</code>.
     */
    public void setStoryContent(String storyContent) {
        this.storyContent = storyContent;
    }

    /**
     * Getter for <code>blog_db.view_stories.story_markdown</code>.
     */
    public String getStoryMarkdown() {
        return this.storyMarkdown;
    }

    /**
     * Setter for <code>blog_db.view_stories.story_markdown</code>.
     */
    public void setStoryMarkdown(String storyMarkdown) {
        this.storyMarkdown = storyMarkdown;
    }

    /**
     * Getter for <code>blog_db.view_stories.story_start_date</code>.
     */
    public Timestamp getStoryStartDate() {
        return this.storyStartDate;
    }

    /**
     * Setter for <code>blog_db.view_stories.story_start_date</code>.
     */
    public void setStoryStartDate(Timestamp storyStartDate) {
        this.storyStartDate = storyStartDate;
    }

    /**
     * Getter for <code>blog_db.view_stories.posts</code>.
     */
    public MiniPost[] getPosts() {
        return this.posts;
    }

    /**
     * Setter for <code>blog_db.view_stories.posts</code>.
     */
    public void setPosts(MiniPost[] posts) {
        this.posts = posts;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewStories (");

        sb.append(storyId);
        sb.append(", ").append(storyTitle);
        sb.append(", ").append(storyContent);
        sb.append(", ").append(storyMarkdown);
        sb.append(", ").append(storyStartDate);
        sb.append(", ").append(Arrays.toString(posts));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
