/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables.pojos;


import blog.raubach.database.codegen.enums.HillsType;
import blog.raubach.pojo.MiniPost;
import blog.raubach.pojo.view.PostPerson;

import java.io.Serializable;
import java.util.Arrays;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewHills implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer      hillId;
    private String       hillName;
    private HillsType    hillType;
    private String       hillRegion;
    private String       hillUrl;
    private Double       hillLatitude;
    private Double       hillLongitude;
    private Double       hillElevation;
    private MiniPost[]   posts;
    private PostPerson[] people;

    public ViewHills() {}

    public ViewHills(ViewHills value) {
        this.hillId = value.hillId;
        this.hillName = value.hillName;
        this.hillType = value.hillType;
        this.hillRegion = value.hillRegion;
        this.hillUrl = value.hillUrl;
        this.hillLatitude = value.hillLatitude;
        this.hillLongitude = value.hillLongitude;
        this.hillElevation = value.hillElevation;
        this.posts = value.posts;
        this.people = value.people;
    }

    public ViewHills(
        Integer      hillId,
        String       hillName,
        HillsType    hillType,
        String       hillRegion,
        String       hillUrl,
        Double       hillLatitude,
        Double       hillLongitude,
        Double       hillElevation,
        MiniPost[]   posts,
        PostPerson[] people
    ) {
        this.hillId = hillId;
        this.hillName = hillName;
        this.hillType = hillType;
        this.hillRegion = hillRegion;
        this.hillUrl = hillUrl;
        this.hillLatitude = hillLatitude;
        this.hillLongitude = hillLongitude;
        this.hillElevation = hillElevation;
        this.posts = posts;
        this.people = people;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_id</code>.
     */
    public Integer getHillId() {
        return this.hillId;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_id</code>.
     */
    public void setHillId(Integer hillId) {
        this.hillId = hillId;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_name</code>.
     */
    public String getHillName() {
        return this.hillName;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_name</code>.
     */
    public void setHillName(String hillName) {
        this.hillName = hillName;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_type</code>.
     */
    public HillsType getHillType() {
        return this.hillType;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_type</code>.
     */
    public void setHillType(HillsType hillType) {
        this.hillType = hillType;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_region</code>.
     */
    public String getHillRegion() {
        return this.hillRegion;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_region</code>.
     */
    public void setHillRegion(String hillRegion) {
        this.hillRegion = hillRegion;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_url</code>.
     */
    public String getHillUrl() {
        return this.hillUrl;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_url</code>.
     */
    public void setHillUrl(String hillUrl) {
        this.hillUrl = hillUrl;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_latitude</code>.
     */
    public Double getHillLatitude() {
        return this.hillLatitude;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_latitude</code>.
     */
    public void setHillLatitude(Double hillLatitude) {
        this.hillLatitude = hillLatitude;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_longitude</code>.
     */
    public Double getHillLongitude() {
        return this.hillLongitude;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_longitude</code>.
     */
    public void setHillLongitude(Double hillLongitude) {
        this.hillLongitude = hillLongitude;
    }

    /**
     * Getter for <code>blog_db.view_hills.hill_elevation</code>.
     */
    public Double getHillElevation() {
        return this.hillElevation;
    }

    /**
     * Setter for <code>blog_db.view_hills.hill_elevation</code>.
     */
    public void setHillElevation(Double hillElevation) {
        this.hillElevation = hillElevation;
    }

    /**
     * Getter for <code>blog_db.view_hills.posts</code>.
     */
    public MiniPost[] getPosts() {
        return this.posts;
    }

    /**
     * Setter for <code>blog_db.view_hills.posts</code>.
     */
    public void setPosts(MiniPost[] posts) {
        this.posts = posts;
    }

    /**
     * Getter for <code>blog_db.view_hills.people</code>.
     */
    public PostPerson[] getPeople() {
        return this.people;
    }

    /**
     * Setter for <code>blog_db.view_hills.people</code>.
     */
    public void setPeople(PostPerson[] people) {
        this.people = people;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewHills (");

        sb.append(hillId);
        sb.append(", ").append(hillName);
        sb.append(", ").append(hillType);
        sb.append(", ").append(hillRegion);
        sb.append(", ").append(hillUrl);
        sb.append(", ").append(hillLatitude);
        sb.append(", ").append(hillLongitude);
        sb.append(", ").append(hillElevation);
        sb.append(", ").append(Arrays.toString(posts));
        sb.append(", ").append(Arrays.toString(people));

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
