/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen;


import blog.raubach.database.codegen.tables.Hikeratings;
import blog.raubach.database.codegen.tables.Hikestats;
import blog.raubach.database.codegen.tables.HillIndividuals;
import blog.raubach.database.codegen.tables.Hills;
import blog.raubach.database.codegen.tables.ImageDetails;
import blog.raubach.database.codegen.tables.Images;
import blog.raubach.database.codegen.tables.Individuals;
import blog.raubach.database.codegen.tables.Posthills;
import blog.raubach.database.codegen.tables.Postimages;
import blog.raubach.database.codegen.tables.Posts;
import blog.raubach.database.codegen.tables.Postsites;
import blog.raubach.database.codegen.tables.Postusers;
import blog.raubach.database.codegen.tables.Postvideos;
import blog.raubach.database.codegen.tables.Relationships;
import blog.raubach.database.codegen.tables.SchemaVersion;
import blog.raubach.database.codegen.tables.Sites;
import blog.raubach.database.codegen.tables.Stories;
import blog.raubach.database.codegen.tables.Storyposts;
import blog.raubach.database.codegen.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db</code>
     */
    public static final BlogDb BLOG_DB = new BlogDb();

    /**
     * No further instances allowed
     */
    private BlogDb() {
        super("blog_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Hikeratings.HIKERATINGS,
            Hikestats.HIKESTATS,
            HillIndividuals.HILL_INDIVIDUALS,
            Hills.HILLS,
            ImageDetails.IMAGE_DETAILS,
            Images.IMAGES,
            Individuals.INDIVIDUALS,
            Posthills.POSTHILLS,
            Postimages.POSTIMAGES,
            Posts.POSTS,
            Postsites.POSTSITES,
            Postusers.POSTUSERS,
            Postvideos.POSTVIDEOS,
            Relationships.RELATIONSHIPS,
            SchemaVersion.SCHEMA_VERSION,
            Sites.SITES,
            Stories.STORIES,
            Storyposts.STORYPOSTS,
            Users.USERS
        );
    }
    // @formatter:on
}
