/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.HikeratingsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hikeratings extends TableImpl<HikeratingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db.hikeratings</code>
     */
    public static final Hikeratings HIKERATINGS = new Hikeratings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HikeratingsRecord> getRecordType() {
        return HikeratingsRecord.class;
    }

    /**
     * The column <code>blog_db.hikeratings.post_id</code>.
     */
    public final TableField<HikeratingsRecord, Integer> POST_ID = createField(DSL.name("post_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.hikeratings.weather</code>.
     */
    public final TableField<HikeratingsRecord, Short> WEATHER = createField(DSL.name("weather"), SQLDataType.SMALLINT.defaultValue(DSL.inline("1", SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>blog_db.hikeratings.path</code>.
     */
    public final TableField<HikeratingsRecord, Short> PATH = createField(DSL.name("path"), SQLDataType.SMALLINT.defaultValue(DSL.inline("1", SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>blog_db.hikeratings.view</code>.
     */
    public final TableField<HikeratingsRecord, Short> VIEW = createField(DSL.name("view"), SQLDataType.SMALLINT.defaultValue(DSL.inline("1", SQLDataType.SMALLINT)), this, "");

    private Hikeratings(Name alias, Table<HikeratingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hikeratings(Name alias, Table<HikeratingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>blog_db.hikeratings</code> table reference
     */
    public Hikeratings(String alias) {
        this(DSL.name(alias), HIKERATINGS);
    }

    /**
     * Create an aliased <code>blog_db.hikeratings</code> table reference
     */
    public Hikeratings(Name alias) {
        this(alias, HIKERATINGS);
    }

    /**
     * Create a <code>blog_db.hikeratings</code> table reference
     */
    public Hikeratings() {
        this(DSL.name("hikeratings"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BlogDb.BLOG_DB;
    }

    @Override
    public UniqueKey<HikeratingsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Hikeratings.HIKERATINGS, DSL.name("KEY_hikeratings_PRIMARY"), new TableField[] { Hikeratings.HIKERATINGS.POST_ID }, true);
    }

    @Override
    public Hikeratings as(String alias) {
        return new Hikeratings(DSL.name(alias), this);
    }

    @Override
    public Hikeratings as(Name alias) {
        return new Hikeratings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hikeratings rename(String name) {
        return new Hikeratings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hikeratings rename(Name name) {
        return new Hikeratings(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Short, Short, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
    // @formatter:on
}
