/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.PostvideosRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postvideos extends TableImpl<PostvideosRecord> {

    private static final long serialVersionUID = -267408503;

    /**
     * The reference instance of <code>blog_db.postvideos</code>
     */
    public static final Postvideos POSTVIDEOS = new Postvideos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostvideosRecord> getRecordType() {
        return PostvideosRecord.class;
    }

    /**
     * The column <code>blog_db.postvideos.post_id</code>.
     */
    public final TableField<PostvideosRecord, Integer> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.postvideos.video_path</code>.
     */
    public final TableField<PostvideosRecord, String> VIDEO_PATH = createField("video_path", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>blog_db.postvideos.created_on</code>.
     */
    public final TableField<PostvideosRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>blog_db.postvideos.updated_on</code>.
     */
    public final TableField<PostvideosRecord, Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>blog_db.postvideos</code> table reference
     */
    public Postvideos() {
        this(DSL.name("postvideos"), null);
    }

    /**
     * Create an aliased <code>blog_db.postvideos</code> table reference
     */
    public Postvideos(String alias) {
        this(DSL.name(alias), POSTVIDEOS);
    }

    /**
     * Create an aliased <code>blog_db.postvideos</code> table reference
     */
    public Postvideos(Name alias) {
        this(alias, POSTVIDEOS);
    }

    private Postvideos(Name alias, Table<PostvideosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Postvideos(Name alias, Table<PostvideosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostvideosRecord> getPrimaryKey() {
        return Internal.createUniqueKey(blog.raubach.database.codegen.tables.Postvideos.POSTVIDEOS, "KEY_postvideos_PRIMARY", blog.raubach.database.codegen.tables.Postvideos.POSTVIDEOS.POST_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostvideosRecord>> getKeys() {
        return Arrays.<UniqueKey<PostvideosRecord>>asList(
              Internal.createUniqueKey(blog.raubach.database.codegen.tables.Postvideos.POSTVIDEOS, "KEY_postvideos_PRIMARY", blog.raubach.database.codegen.tables.Postvideos.POSTVIDEOS.POST_ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Postvideos as(String alias) {
        return new Postvideos(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Postvideos as(Name alias) {
        return new Postvideos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Postvideos rename(String name) {
        return new Postvideos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Postvideos rename(Name name) {
        return new Postvideos(name, null);
    }
// @formatter:on
}
