/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.PosthillsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Posthills extends TableImpl<PosthillsRecord> {

    private static final long serialVersionUID = -664203411;

    /**
     * The reference instance of <code>blog_db.posthills</code>
     */
    public static final Posthills POSTHILLS = new Posthills();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PosthillsRecord> getRecordType() {
        return PosthillsRecord.class;
    }

    /**
     * The column <code>blog_db.posthills.post_id</code>.
     */
    public final TableField<PosthillsRecord, Integer> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.posthills.hill_id</code>.
     */
    public final TableField<PosthillsRecord, Integer> HILL_ID = createField("hill_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>blog_db.posthills</code> table reference
     */
    public Posthills() {
        this(DSL.name("posthills"), null);
    }

    /**
     * Create an aliased <code>blog_db.posthills</code> table reference
     */
    public Posthills(String alias) {
        this(DSL.name(alias), POSTHILLS);
    }

    /**
     * Create an aliased <code>blog_db.posthills</code> table reference
     */
    public Posthills(Name alias) {
        this(alias, POSTHILLS);
    }

    private Posthills(Name alias, Table<PosthillsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Posthills(Name alias, Table<PosthillsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PosthillsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(blog.raubach.database.codegen.tables.Posthills.POSTHILLS, "KEY_posthills_PRIMARY", blog.raubach.database.codegen.tables.Posthills.POSTHILLS.POST_ID, blog.raubach.database.codegen.tables.Posthills.POSTHILLS.HILL_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PosthillsRecord>> getKeys() {
        return Arrays.<UniqueKey<PosthillsRecord>>asList(
              Internal.createUniqueKey(blog.raubach.database.codegen.tables.Posthills.POSTHILLS, "KEY_posthills_PRIMARY", blog.raubach.database.codegen.tables.Posthills.POSTHILLS.POST_ID, blog.raubach.database.codegen.tables.Posthills.POSTHILLS.HILL_ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Posthills as(String alias) {
        return new Posthills(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Posthills as(Name alias) {
        return new Posthills(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Posthills rename(String name) {
        return new Posthills(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Posthills rename(Name name) {
        return new Posthills(name, null);
    }
// @formatter:on
}
