/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.PostimagesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Postimages extends TableImpl<PostimagesRecord> {

    private static final long serialVersionUID = 395390537;

    /**
     * The reference instance of <code>blog_db.postimages</code>
     */
    public static final Postimages POSTIMAGES = new Postimages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostimagesRecord> getRecordType() {
        return PostimagesRecord.class;
    }

    /**
     * The column <code>blog_db.postimages.post_id</code>.
     */
    public final TableField<PostimagesRecord, Integer> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.postimages.image_id</code>.
     */
    public final TableField<PostimagesRecord, Integer> IMAGE_ID = createField("image_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.postimages.is_primary</code>.
     */
    public final TableField<PostimagesRecord, Boolean> IS_PRIMARY = createField("is_primary", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>blog_db.postimages.description</code>.
     */
    public final TableField<PostimagesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>blog_db.postimages</code> table reference
     */
    public Postimages() {
        this(DSL.name("postimages"), null);
    }

    /**
     * Create an aliased <code>blog_db.postimages</code> table reference
     */
    public Postimages(String alias) {
        this(DSL.name(alias), POSTIMAGES);
    }

    /**
     * Create an aliased <code>blog_db.postimages</code> table reference
     */
    public Postimages(Name alias) {
        this(alias, POSTIMAGES);
    }

    private Postimages(Name alias, Table<PostimagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Postimages(Name alias, Table<PostimagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostimagesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(blog.raubach.database.codegen.tables.Postimages.POSTIMAGES, "KEY_postimages_PRIMARY", blog.raubach.database.codegen.tables.Postimages.POSTIMAGES.POST_ID, blog.raubach.database.codegen.tables.Postimages.POSTIMAGES.IMAGE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostimagesRecord>> getKeys() {
        return Arrays.<UniqueKey<PostimagesRecord>>asList(
              Internal.createUniqueKey(blog.raubach.database.codegen.tables.Postimages.POSTIMAGES, "KEY_postimages_PRIMARY", blog.raubach.database.codegen.tables.Postimages.POSTIMAGES.POST_ID, blog.raubach.database.codegen.tables.Postimages.POSTIMAGES.IMAGE_ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Postimages as(String alias) {
        return new Postimages(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Postimages as(Name alias) {
        return new Postimages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Postimages rename(String name) {
        return new Postimages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Postimages rename(Name name) {
        return new Postimages(name, null);
    }
// @formatter:on
}
