/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.StorypostsRecord;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Storyposts extends TableImpl<StorypostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db.storyposts</code>
     */
    public static final Storyposts STORYPOSTS = new Storyposts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StorypostsRecord> getRecordType() {
        return StorypostsRecord.class;
    }

    /**
     * The column <code>blog_db.storyposts.story_id</code>.
     */
    public final TableField<StorypostsRecord, Integer> STORY_ID = createField(DSL.name("story_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.storyposts.post_id</code>.
     */
    public final TableField<StorypostsRecord, Integer> POST_ID = createField(DSL.name("post_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Storyposts(Name alias, Table<StorypostsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Storyposts(Name alias, Table<StorypostsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>blog_db.storyposts</code> table reference
     */
    public Storyposts(String alias) {
        this(DSL.name(alias), STORYPOSTS);
    }

    /**
     * Create an aliased <code>blog_db.storyposts</code> table reference
     */
    public Storyposts(Name alias) {
        this(alias, STORYPOSTS);
    }

    /**
     * Create a <code>blog_db.storyposts</code> table reference
     */
    public Storyposts() {
        this(DSL.name("storyposts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BlogDb.BLOG_DB;
    }

    @Override
    public UniqueKey<StorypostsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Storyposts.STORYPOSTS, DSL.name("KEY_storyposts_PRIMARY"), new TableField[] { Storyposts.STORYPOSTS.STORY_ID, Storyposts.STORYPOSTS.POST_ID }, true);
    }

    @Override
    public Storyposts as(String alias) {
        return new Storyposts(DSL.name(alias), this);
    }

    @Override
    public Storyposts as(Name alias) {
        return new Storyposts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Storyposts rename(String name) {
        return new Storyposts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Storyposts rename(Name name) {
        return new Storyposts(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
    // @formatter:on
}
