/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.StoriesRecord;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stories extends TableImpl<StoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db.stories</code>
     */
    public static final Stories STORIES = new Stories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StoriesRecord> getRecordType() {
        return StoriesRecord.class;
    }

    /**
     * The column <code>blog_db.stories.id</code>.
     */
    public final TableField<StoriesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.stories.title</code>.
     */
    public final TableField<StoriesRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>blog_db.stories.content</code>.
     */
    public final TableField<StoriesRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.stories.content_markdown</code>.
     */
    public final TableField<StoriesRecord, String> CONTENT_MARKDOWN = createField(DSL.name("content_markdown"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.stories.created_on</code>.
     */
    public final TableField<StoriesRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>blog_db.stories.updated_on</code>.
     */
    public final TableField<StoriesRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private Stories(Name alias, Table<StoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stories(Name alias, Table<StoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>blog_db.stories</code> table reference
     */
    public Stories(String alias) {
        this(DSL.name(alias), STORIES);
    }

    /**
     * Create an aliased <code>blog_db.stories</code> table reference
     */
    public Stories(Name alias) {
        this(alias, STORIES);
    }

    /**
     * Create a <code>blog_db.stories</code> table reference
     */
    public Stories() {
        this(DSL.name("stories"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BlogDb.BLOG_DB;
    }

    @Override
    public Identity<StoriesRecord, Integer> getIdentity() {
        return (Identity<StoriesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<StoriesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Stories.STORIES, DSL.name("KEY_stories_PRIMARY"), new TableField[] { Stories.STORIES.ID }, true);
    }

    @Override
    public Stories as(String alias) {
        return new Stories(DSL.name(alias), this);
    }

    @Override
    public Stories as(Name alias) {
        return new Stories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stories rename(String name) {
        return new Stories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stories rename(Name name) {
        return new Stories(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
    // @formatter:on
}
