/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.binding.GrountypeArrayBinding;
import blog.raubach.database.binding.IntArrayBinding;
import blog.raubach.database.binding.SiteFacilitiesBinding;
import blog.raubach.database.binding.SiteRatingBinding;
import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.enums.PostsitesGroundtype;
import blog.raubach.database.codegen.enums.SitesSitetype;
import blog.raubach.database.codegen.tables.records.ViewSitesRecord;
import blog.raubach.pojo.SiteFacilities;
import blog.raubach.pojo.SiteRating;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSites extends TableImpl<ViewSitesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db.view_sites</code>
     */
    public static final ViewSites VIEW_SITES = new ViewSites();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewSitesRecord> getRecordType() {
        return ViewSitesRecord.class;
    }

    /**
     * The column <code>blog_db.view_sites.id</code>.
     */
    public final TableField<ViewSitesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blog_db.view_sites.name</code>.
     */
    public final TableField<ViewSitesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>blog_db.view_sites.description</code>.
     */
    public final TableField<ViewSitesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.view_sites.sitetype</code>.
     */
    public final TableField<ViewSitesRecord, SitesSitetype> SITETYPE = createField(DSL.name("sitetype"), SQLDataType.VARCHAR(8).nullable(false).defaultValue(DSL.inline("campsite", SQLDataType.VARCHAR)), this, "", new EnumConverter<String, SitesSitetype>(String.class, SitesSitetype.class));

    /**
     * The column <code>blog_db.view_sites.latitude</code>.
     */
    public final TableField<ViewSitesRecord, Double> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>blog_db.view_sites.longitude</code>.
     */
    public final TableField<ViewSitesRecord, Double> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>blog_db.view_sites.elevation</code>.
     */
    public final TableField<ViewSitesRecord, Double> ELEVATION = createField(DSL.name("elevation"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>blog_db.view_sites.rating</code>.
     */
    public final TableField<ViewSitesRecord, SiteRating> RATING = createField(DSL.name("rating"), SQLDataType.JSON.nullable(false), this, "", new SiteRatingBinding());

    /**
     * The column <code>blog_db.view_sites.facilities</code>.
     */
    public final TableField<ViewSitesRecord, SiteFacilities> FACILITIES = createField(DSL.name("facilities"), SQLDataType.JSON.nullable(false), this, "", new SiteFacilitiesBinding());

    /**
     * The column <code>blog_db.view_sites.created_on</code>.
     */
    public final TableField<ViewSitesRecord, Timestamp> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>blog_db.view_sites.updated_on</code>.
     */
    public final TableField<ViewSitesRecord, Timestamp> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>blog_db.view_sites.groundtypes</code>.
     */
    public final TableField<ViewSitesRecord, PostsitesGroundtype[]> GROUNDTYPES = createField(DSL.name("groundtypes"), SQLDataType.JSON, this, "", new GrountypeArrayBinding());

    /**
     * The column <code>blog_db.view_sites.post_ids</code>.
     */
    public final TableField<ViewSitesRecord, Integer[]> POST_IDS = createField(DSL.name("post_ids"), SQLDataType.JSON, this, "", new IntArrayBinding());

    private ViewSites(Name alias, Table<ViewSitesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewSites(Name alias, Table<ViewSitesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `view_sites` as select `blog`.`sites`.`id` AS `id`,`blog`.`sites`.`name` AS `name`,`blog`.`sites`.`description` AS `description`,`blog`.`sites`.`sitetype` AS `sitetype`,`blog`.`sites`.`latitude` AS `latitude`,`blog`.`sites`.`longitude` AS `longitude`,`blog`.`sites`.`elevation` AS `elevation`,`blog`.`sites`.`rating` AS `rating`,`blog`.`sites`.`facilities` AS `facilities`,`blog`.`sites`.`created_on` AS `created_on`,`blog`.`sites`.`updated_on` AS `updated_on`,json_arrayagg(`blog`.`postsites`.`groundtype`) AS `groundtypes`,json_arrayagg(`blog`.`postsites`.`post_id`) AS `post_ids` from (`blog`.`sites` left join `blog`.`postsites` on((`blog`.`postsites`.`site_id` = `blog`.`sites`.`id`))) group by `blog`.`sites`.`id`"));
    }

    /**
     * Create an aliased <code>blog_db.view_sites</code> table reference
     */
    public ViewSites(String alias) {
        this(DSL.name(alias), VIEW_SITES);
    }

    /**
     * Create an aliased <code>blog_db.view_sites</code> table reference
     */
    public ViewSites(Name alias) {
        this(alias, VIEW_SITES);
    }

    /**
     * Create a <code>blog_db.view_sites</code> table reference
     */
    public ViewSites() {
        this(DSL.name("view_sites"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BlogDb.BLOG_DB;
    }

    @Override
    public ViewSites as(String alias) {
        return new ViewSites(DSL.name(alias), this);
    }

    @Override
    public ViewSites as(Name alias) {
        return new ViewSites(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewSites rename(String name) {
        return new ViewSites(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewSites rename(Name name) {
        return new ViewSites(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, SitesSitetype, Double, Double, Double, SiteRating, SiteFacilities, Timestamp, Timestamp, PostsitesGroundtype[], Integer[]> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
    // @formatter:on
}
