/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.binding.MiniPostArrayBinding;
import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.tables.records.ViewStoriesRecord;
import blog.raubach.pojo.MiniPost;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewStories extends TableImpl<ViewStoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db.view_stories</code>
     */
    public static final ViewStories VIEW_STORIES = new ViewStories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewStoriesRecord> getRecordType() {
        return ViewStoriesRecord.class;
    }

    /**
     * The column <code>blog_db.view_stories.story_id</code>.
     */
    public final TableField<ViewStoriesRecord, Integer> STORY_ID = createField(DSL.name("story_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blog_db.view_stories.story_title</code>.
     */
    public final TableField<ViewStoriesRecord, String> STORY_TITLE = createField(DSL.name("story_title"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.view_stories.story_content</code>.
     */
    public final TableField<ViewStoriesRecord, String> STORY_CONTENT = createField(DSL.name("story_content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.view_stories.story_markdown</code>.
     */
    public final TableField<ViewStoriesRecord, String> STORY_MARKDOWN = createField(DSL.name("story_markdown"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.view_stories.story_start_date</code>.
     */
    public final TableField<ViewStoriesRecord, Timestamp> STORY_START_DATE = createField(DSL.name("story_start_date"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>blog_db.view_stories.posts</code>.
     */
    public final TableField<ViewStoriesRecord, MiniPost[]> POSTS = createField(DSL.name("posts"), SQLDataType.JSON, this, "", new MiniPostArrayBinding());

    private ViewStories(Name alias, Table<ViewStoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewStories(Name alias, Table<ViewStoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `view_stories` as select `blog`.`stories`.`id` AS `story_id`,`blog`.`stories`.`title` AS `story_title`,`blog`.`stories`.`content` AS `story_content`,`blog`.`stories`.`content_markdown` AS `story_markdown`,`blog`.`stories`.`created_on` AS `story_start_date`,(select json_arrayagg(json_object('id',`blog`.`posts`.`id`,'title',`blog`.`posts`.`title`,'primaryImageId',`blog`.`images`.`id`,'primaryImagePath',`blog`.`images`.`path`,'visible',`blog`.`posts`.`visible`,'type',`blog`.`posts`.`type`)) from (((`blog`.`posts` left join `blog`.`postimages` on(((`blog`.`posts`.`id` = `blog`.`postimages`.`post_id`) and (`blog`.`postimages`.`is_primary` = 1)))) left join `blog`.`images` on((`blog`.`images`.`id` = `blog`.`postimages`.`image_id`))) left join `blog`.`storyposts` on((`blog`.`storyposts`.`post_id` = `blog`.`posts`.`id`))) where (`blog`.`storyposts`.`story_id` = `blog`.`stories`.`id`)) AS `posts` from `blog`.`stories`"));
    }

    /**
     * Create an aliased <code>blog_db.view_stories</code> table reference
     */
    public ViewStories(String alias) {
        this(DSL.name(alias), VIEW_STORIES);
    }

    /**
     * Create an aliased <code>blog_db.view_stories</code> table reference
     */
    public ViewStories(Name alias) {
        this(alias, VIEW_STORIES);
    }

    /**
     * Create a <code>blog_db.view_stories</code> table reference
     */
    public ViewStories() {
        this(DSL.name("view_stories"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BlogDb.BLOG_DB;
    }

    @Override
    public ViewStories as(String alias) {
        return new ViewStories(DSL.name(alias), this);
    }

    @Override
    public ViewStories as(Name alias) {
        return new ViewStories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewStories rename(String name) {
        return new ViewStories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewStories rename(Name name) {
        return new ViewStories(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Timestamp, MiniPost[]> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
    // @formatter:on
}
