/*
 * This file is generated by jOOQ.
 */
package blog.raubach.database.codegen.tables;


import blog.raubach.database.binding.MiniPostArrayBinding;
import blog.raubach.database.binding.PostPersonArrayBinding;
import blog.raubach.database.codegen.BlogDb;
import blog.raubach.database.codegen.enums.HillsType;
import blog.raubach.database.codegen.tables.records.ViewHillsRecord;
import blog.raubach.pojo.MiniPost;
import blog.raubach.pojo.view.PostPerson;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


// @formatter:off
/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewHills extends TableImpl<ViewHillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog_db.view_hills</code>
     */
    public static final ViewHills VIEW_HILLS = new ViewHills();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewHillsRecord> getRecordType() {
        return ViewHillsRecord.class;
    }

    /**
     * The column <code>blog_db.view_hills.hill_id</code>.
     */
    public final TableField<ViewHillsRecord, Integer> HILL_ID = createField(DSL.name("hill_id"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>blog_db.view_hills.hill_name</code>.
     */
    public final TableField<ViewHillsRecord, String> HILL_NAME = createField(DSL.name("hill_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.view_hills.hill_type</code>.
     */
    public final TableField<ViewHillsRecord, HillsType> HILL_TYPE = createField(DSL.name("hill_type"), SQLDataType.VARCHAR(10).defaultValue(DSL.inline("other", SQLDataType.VARCHAR)), this, "", new EnumConverter<String, HillsType>(String.class, HillsType.class));

    /**
     * The column <code>blog_db.view_hills.hill_region</code>.
     */
    public final TableField<ViewHillsRecord, String> HILL_REGION = createField(DSL.name("hill_region"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.view_hills.hill_url</code>.
     */
    public final TableField<ViewHillsRecord, String> HILL_URL = createField(DSL.name("hill_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.view_hills.hill_latitude</code>.
     */
    public final TableField<ViewHillsRecord, Double> HILL_LATITUDE = createField(DSL.name("hill_latitude"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>blog_db.view_hills.hill_longitude</code>.
     */
    public final TableField<ViewHillsRecord, Double> HILL_LONGITUDE = createField(DSL.name("hill_longitude"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>blog_db.view_hills.hill_elevation</code>.
     */
    public final TableField<ViewHillsRecord, Double> HILL_ELEVATION = createField(DSL.name("hill_elevation"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>blog_db.view_hills.posts</code>.
     */
    public final TableField<ViewHillsRecord, MiniPost[]> POSTS = createField(DSL.name("posts"), SQLDataType.JSON, this, "", new MiniPostArrayBinding());

    /**
     * The column <code>blog_db.view_hills.people</code>.
     */
    public final TableField<ViewHillsRecord, PostPerson[]> PEOPLE = createField(DSL.name("people"), SQLDataType.JSON, this, "", new PostPersonArrayBinding());

    private ViewHills(Name alias, Table<ViewHillsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewHills(Name alias, Table<ViewHillsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `view_hills` as select `blog`.`hills`.`id` AS `hill_id`,`blog`.`hills`.`name` AS `hill_name`,`blog`.`hills`.`type` AS `hill_type`,`blog`.`hills`.`region` AS `hill_region`,`blog`.`hills`.`url` AS `hill_url`,`blog`.`hills`.`latitude` AS `hill_latitude`,`blog`.`hills`.`longitude` AS `hill_longitude`,`blog`.`hills`.`elevation` AS `hill_elevation`,(select json_arrayagg(json_object('id',`blog`.`posts`.`id`,'title',`blog`.`posts`.`title`,'primaryImageId',`blog`.`images`.`id`,'primaryImagePath',`blog`.`images`.`path`,'visible',`blog`.`posts`.`visible`)) from (((`blog`.`posts` left join `blog`.`postimages` on(((`blog`.`posts`.`id` = `blog`.`postimages`.`post_id`) and (`blog`.`postimages`.`is_primary` = 1)))) left join `blog`.`images` on((`blog`.`images`.`id` = `blog`.`postimages`.`image_id`))) left join `blog`.`posthills` on((`blog`.`posthills`.`post_id` = `blog`.`posts`.`id`))) where (`blog`.`posthills`.`hill_id` = `blog`.`hills`.`id`)) AS `posts`,(select json_arrayagg(json_object('personId',`blog`.`individuals`.`id`,'personName',`blog`.`individuals`.`name`)) from (((`blog`.`posts` left join `blog`.`post_individuals` on((`blog`.`posts`.`id` = `blog`.`post_individuals`.`post_id`))) left join `blog`.`individuals` on((`blog`.`individuals`.`id` = `blog`.`post_individuals`.`individual_id`))) left join `blog`.`posthills` on((`blog`.`posthills`.`post_id` = `blog`.`posts`.`id`))) where (`blog`.`posthills`.`hill_id` = `blog`.`hills`.`id`)) AS `people` from `blog`.`hills`"));
    }

    /**
     * Create an aliased <code>blog_db.view_hills</code> table reference
     */
    public ViewHills(String alias) {
        this(DSL.name(alias), VIEW_HILLS);
    }

    /**
     * Create an aliased <code>blog_db.view_hills</code> table reference
     */
    public ViewHills(Name alias) {
        this(alias, VIEW_HILLS);
    }

    /**
     * Create a <code>blog_db.view_hills</code> table reference
     */
    public ViewHills() {
        this(DSL.name("view_hills"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BlogDb.BLOG_DB;
    }

    @Override
    public ViewHills as(String alias) {
        return new ViewHills(DSL.name(alias), this);
    }

    @Override
    public ViewHills as(Name alias) {
        return new ViewHills(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewHills rename(String name) {
        return new ViewHills(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewHills rename(Name name) {
        return new ViewHills(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, HillsType, String, String, Double, Double, Double, MiniPost[], PostPerson[]> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
    // @formatter:on
}
